insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('1','Marquis Dendy','SR','Florida','8.43','+2.3','1 (1)','10');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('2','Jarrion Lawson','JR','Arkansas','8.34','+0.2','2 (1)','8');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('3','Roelf Pienaar','SO','Arkansas State','8.01','+1.6','2 (2)','6');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('4','Jonathan Addison','JR','North Carolina St.','7.99','+2.3','2 (3)','5');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('5','Adoree Jackson','FR','USC','7.91','+1.9','2 (4)','4');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('6','Laderrick Ward','SR','SIU-Edwardsville','7.82','+2.5','1 (2)','3');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('7','Walter Jones','FR','California','7.79','+1.9','1 (3)','2');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('8','Ventavius Sears','SO','Western Kentucky','7.76','+1.9','1 (4)','1');
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('9','Cameron Echols-Luper','SO','TCU','7.73','+2.0','1 (5)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('10','Nate Moore','FR','Oregon','7.69','+1.7','2 (5)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('11','Ifeanyichukwu Otuonye','JR','Kansas State','7.69','+2.1','1 (6)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('12','Stefan Brits','JR','Florida State','7.66','+1.5','1 (7)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('13','Trevor Ferguson','SR','Oregon','7.61','+2.2','1 (8)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('14','Jalen Ramsey','SO','Florida State','7.60','+1.2','1 (9)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('15','Blake Smith','SR','SE Missouri','7.56','+2.5','2 (6)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('16','Bryan McBride','SR','Arizona State','7.51','+0.5','1 (10)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('17','Kenneth Fisher','SO','Bethune-Cookman','7.51','+2.6','1 (11)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('18','Jarrett Samuels','JR','Louisiana Tech','7.50','+1.4','2 (7)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('19','Devon Breaux','JR','Tulane','7.44','+0.9','2 (8)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('20','Jerome Wilson','SR','Texas Tech','7.44','+1.7','1 (12)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('21','Paul Madzivire','SR','Florida State','7.39','+0.7','2 (9)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('22','Terence Boyd','SR','Kentucky','7.32','+2.1','2 (10)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('23','Zack Bazile','FR','Ohio State','7.31','+1.8','2 (11)',null);
insert into m_LJ_final_2015 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('24','Jordan Latimer','FR','Akron','7.07','+2.9','2 (12)',null);

insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('1','Marquis Dendy','SR','Florida','17.71','2.4','1 (1)','10');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('2','Latario Collie','JR','Texas A&M','17.01','3.8','2 (1)','8');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('3','Donald Scott','SR','Eastern Michigan','16.83','2.5','1 (2)','6');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('4','Ben Williams','SO','Louisville','16.74','1.4','1 (3)','5');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('5','Jonathan Reid','SR','Florida State','16.52','2.2','2 (2)','4');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('6','Jeremiah Green','SO','Alabama','16.50','4.2','2 (3)','3');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('7','Clive Pullen','SO','Arkansas','16.27','4.2','2 (4)','2');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('8','Steve Waithe','SR','Penn State','16.26','3.4','1 (4)','1');
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('9','Matthew Oneal','JR','South Florida','16.12','1.3','1 (5)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('10','Felix Obi','SO','Baylor','16.07','2.0','1 (6)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('11','John Warren','FR','Missouri','15.99','1.7','2 (5)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('12','Olabanji Asekun','SR','Texas A&M','15.97','4.3','2 (6)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('13','Nate Moore','FR','Oregon','15.96','4.8','2 (7)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('14','Shawn Johnson','JR','Auburn','15.92','1.7','1 (7)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('15','Anthony Campbell','JR','Charlotte','15.83','2.7','1 (8)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('16','Josh Dixon','JR','Arizona State','15.81','2.5','1 (9)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('17','Scotty Newton','FR','TCU','15.75','3.7','1 (10)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('18','Shai Carpenter','SR','Clemson','15.75','3.0','2 (8)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('19','John-Patrick Friday','JR','Miami','15.69','2.8','2 (9)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('20','Luke James','SR','Southern Illinois','15.52','2.6','2 (10)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('21','Chris Martin','SO','SE Missouri','15.47','3.0','2 (11)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('22','Babatunde Amosu','SR','Iowa','15.45','2.3','1 (11)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values ('23','Ryan Satchell','SR','Virginia','15.37','2.7','2 (12)',null);
insert into m_TJ_final_2015 (Place,Name,YEAR,Team,Mark,Wind,"Flight(pl)",Score) values (null,'Willie Alexander','SO','Long Beach St.','FOUL',null,'1',null);

insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Jacorian Duffield','SR','Texas Tech','2.28','1 (1)','10');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','Bradley Adkins','JR','Texas Tech','2.25','1 (2)','8');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Avion Jones','JR','East Carolina','2.25','1 (3)','6');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Marcus Jackson','SR','Miss State','2.22','1 (4)','5');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Wally Ellenson','JR','Marquette','2.19','1 (5)','4');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Bryan McBride','SR','Arizona State','2.19','1 (6)','3');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('7','James White','SR','Nebraska','2.19','1 (7)','2');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Randall Cunningham','FR','USC','2.16','1 (8)','1');
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Shawn Johnson','JR','Auburn','2.16','1 (8)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Torian Ware','SR','Clemson','2.16','1 (10)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','Trey Culver','FR','Texas Tech','2.16','1 (11)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Gemikal Prude','JR','Lipscomb','2.16','1 (12)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Ken LeGassey','SO','Arkansas','2.16','1 (13)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Branden Greene','JR','Mississippi','2.12','1 (14)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Justin Fondren','JR','Alabama','2.12','1 (14)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','EdnullRicus Williams','SO','Bethune-Cookman','2.12','1 (16)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('17','Roland Sales','JR','UT-Arlington','2.12','1 (17)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('18','NaTron Gipson','FR','Kansas State','2.12','1 (18)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('19','Keyth Fightmaster','FR','Samford','2.12','1 (19)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Landon Bartel','FR','Nebraska','2.08','1 (20)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Reggie Nelson','SR','Coastal Carolina','2.08','1 (20)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Michael Monroe','FR','Penn','2.08','1 (20)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('23','Christoff Bryan','FR','Kansas State','2.08','1 (23)',null);
insert into m_HJ_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('24','Adam Aguirre','JR','Mississippi','2.08','1 (24)',null);

insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Shawn Barber','JR','Akron','5.60','1 (1)','10');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','Pauls Pujats','SR','Memphis','5.55','1 (2)','8');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Dylan Duvio','SO','Stanford','5.50','1 (3)','6');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Audie Wyatt','FR','Texas A&M','5.50','1 (4)','5');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Adrian Valles','FR','Cincinnati','5.50','1 (5)','4');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Logan Pflibsen','SR','New Mexico','5.40','1 (6)','3');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Jake Blankenship','JR','Tennessee','5.40','1 (6)','2');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Craig Hunter','SO','Connecticut','5.40','1 (8)','1');
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('9','Chase Wolfle','JR','Texas A&M','5.40','1 (9)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Jake Albright','JR','Kansas','5.30','1 (10)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','Tyler Porter','SR','Tennessee','5.30','1 (11)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Kyle Thompson','SR','Texas Tech','5.30','1 (12)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Nick Meyer','SO','Kansas','5.30','1 (13)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Cory Duggan','SR','Connecticut','5.15','1 (14)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Nate Richartz','SO','Notre Dame','5.15','1 (14)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','David Shepherd','SR','South Florida','5.15','1 (16)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Ethan Sandusky','SR','Arkansas State','5.15','1 (16)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Dylan Bell','JR','Air Force','5.15','1 (16)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Steven Cahoy','SO','Nebraska','5.15','1 (16)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Terry Batemon','SO','Indiana','5.15','1 (20)',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Tray Oates','FR','Samford','NH','1',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Brad Johnson','SO','Virginia Tech','NH','1',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Braydon Bringhurst','SR','BYU','NH','1',null);
insert into m_PV_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Michael Montgomery','SO','Long Beach St.','NH','1',null);

insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Jacorian Duffield','SR','Texas Tech','2.28','1 (1)','10');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','Bradley Adkins','JR','Texas Tech','2.25','1 (2)','8');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Avion Jones','JR','East Carolina','2.25','1 (3)','6');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Marcus Jackson','SR','Miss State','2.22','1 (4)','5');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Wally Ellenson','JR','Marquette','2.19','1 (5)','4');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Bryan McBride','SR','Arizona State','2.19','1 (6)','3');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('7','James White','SR','Nebraska','2.19','1 (7)','2');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Randall Cunningham','FR','USC','2.16','1 (8)','1');
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Shawn Johnson','JR','Auburn','2.16','1 (8)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Torian Ware','SR','Clemson','2.16','1 (10)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','Trey Culver','FR','Texas Tech','2.16','1 (11)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Gemikal Prude','JR','Lipscomb','2.16','1 (12)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Ken LeGassey','SO','Arkansas','2.16','1 (13)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Branden Greene','JR','Mississippi','2.12','1 (14)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Justin Fondren','JR','Alabama','2.12','1 (14)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','EdnullRicus Williams','SO','Bethune-Cookman','2.12','1 (16)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('17','Roland Sales','JR','UT-Arlington','2.12','1 (17)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('18','NaTron Gipson','FR','Kansas State','2.12','1 (18)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('19','Keyth Fightmaster','FR','Samford','2.12','1 (19)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Landon Bartel','FR','Nebraska','2.08','1 (20)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Reggie Nelson','SR','Coastal Carolina','2.08','1 (20)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Michael Monroe','FR','Penn','2.08','1 (20)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('23','Christoff Bryan','FR','Kansas State','2.08','1 (23)',null);
insert into m_HT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('24','Adam Aguirre','JR','Mississippi','2.08','1 (24)',null);

insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Sam Mattis','JR','Penn','62.48','2 (2)','10');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','Tavis Bailey','SR','Tennessee','61.92','2 (1)','8');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Filip Mihaljevic','SO','Virginia','61.29','2 (3)','6');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Antonio James','SR','Michigan State','60.99','2 (4)','5');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Ryan Crouser','SR','Texas','60.18','2 (5)','4');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Jordan Young','SO','Virginia','60.13','2 (6)','3');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('7','Cody Snyder','SR','South Dakota','59.04','1 (1)','2');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Michael Ohakwe','SR','Arizona State','58.49','1 (2)','1');
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('9','Rodney Brown','SR','LSU','58.35','2 (7)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Kole Weldon','SR','Texas Tech','58.20','2 (8)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','Mitchell Cooper','SO','Kansas','58.19','2 (9)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Hayden Reed','SO','Alabama','57.93','1 (3)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Clint Harris','SR','Texas','57.16','1 (4)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Luke Vaughn','SO','Memphis','56.97','1 (5)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('15','Nicholas Percy','FR','Nebraska','56.87','1 (6)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Dalton Rowan','SR','Texas A&M','56.75','2 (10)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('17','Gerhard De Beer','SO','Arizona','56.38','2 (11)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('18','Phillip Jagers','SO','Akron','55.38','1 (7)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('19','Alex Thompson','SR','Wisconsin','54.99','2 (12)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Jan-Louw Kotze','JR','South Alabama','54.96','1 (8)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('21','Nicolai Ceban','FR','Kansas','54.86','1 (9)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('22','Ethan Cochran','SO','California','54.50','1 (10)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('23','Noah Kennedy-White','SO','Penn','53.86','1 (11)',null);
insert into m_DT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Marek Barta','FR','Virginia Tech','FOUL','1',null);

insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Jonathan Jones','SR','Buffalo','20.78','2 (1)','10');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','Darrell Hill','SR','Penn State','20.78','2 (2)','8');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Stipe Zunic','SR','Florida','20.30','2 (3)','6');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Josh Freeman','JR','Southern Illinois','20.15','2 (7)','5');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Ryan Crouser','SR','Texas','19.99','2 (4)','4');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Nick Vena','SR','Georgia','19.80','1 (1)','3');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('7','JC Murasky','JR','Ohio State','19.61','2 (5)','2');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Nicholas Ponzio','FR','USC','19.53','2 (8)','1');
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('9','Filip Mihaljevic','SO','Virginia','19.51','2 (6)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Jordan Young','SO','Virginia','18.97','2 (9)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','Chase Sammons','JR','Oklahoma','18.93','1 (2)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Jan Jeuschede','JR','Iowa State','18.92','2 (10)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Richard Chavez','SR','Arkansas State','18.92','1 (3)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Brad Szypka','SR','Kentucky','18.91','1 (4)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('15','Nicholas Scarvelis','SO','UCLA','18.91','2 (11)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Aaron Castle','SO','Arizona','18.81','1 (5)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('17','Will Lohman','SR','Nebraska','18.81','1 (6)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('18','Stephen Mozia','SR','Cornell','18.77','1 (7)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('19','Matt Babicz','SR','DePaul','18.74','2 (12)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Justin Baker','JR','Northern Iowa','18.59','1 (8)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('21','Luke Johnson','JR','Minnesota','18.45','1 (9)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('22','Chukwuebuka Enekwechi','JR','Purdue','18.43','1 (10)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('23','Cody Riffle','SR','Michigan','18.25','1 (11)',null);
insert into m_SP_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values (null,'Tavis Bailey','SR','Tennessee','FOUL','1',null);

insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('1','Sam Crouser','SR','Oregon','79.19','2 (1)','10');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('2','John Ampomah','JR','Mid. Tenn. State','77.13','2 (2)','8');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('3','Curtis Thompson','FR','Miss State','75.42','1 (1)','6');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('4','Raymond Dykstra','SR','Kentucky','74.90','2 (4)','5');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('5','Ioannis Kyriazis','FR','Texas A&M','73.13','2 (5)','4');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('6','Thomas Lang','JR','Duke','72.50','2 (3)','3');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('7','Matti Mortimore','SO','North Dakota State','72.44','1 (2)','2');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('8','Kyle Bynum','JR','Memphis','70.07','2 (6)','1');
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('9','Curtis Clauson','SR','Washington','70.04','2 (7)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('10','Tomas Guerra','JR','Western Kentucky','69.66','2 (8)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('11','MaCauley Garton','SR','Missouri','68.64','2 (9)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('12','Derek Eager','SR','UCLA','68.27','2 (10)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('13','Michael Criticos','FR','Memphis','68.09','1 (3)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('14','Devin Bogert','SR','Texas A&M','67.94','1 (4)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('15','Robert Smutsky','SO','William and Mary','67.93','1 (5)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('16','Austin Schmidt','FR','North Dakota State','67.75','1 (6)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('17','Thomas Carr','JR','Rutgers','67.17','1 (7)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('18','Thomas Gore-Schreck','SR','UC Santa Barbara','66.12','1 (8)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('19','Chris Mirabelli','FR','Rutgers','65.80','1 (9)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('20','Rasmus Maukonen','SO','UTEP','65.52','1 (10)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('21','Vincent Rentzsch','JR','UMBC','64.71','2 (11)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('22','Kyle Stevens','SR','Washington St.','64.62','1 (11)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('23','Kyle Smith','SR','Virginia','64.33','1 (12)',null);
insert into m_JT_final_2015 (Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('24','Alex Pascal','FR','Missouri','62.69','2 (12)',null);


