insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (1,'Jarrion Lawson','SR','Arkansas','8.15',1.6,'2 (4)','10');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (2,'Roelf Pienaar','JR','Arkansas State','7.93',0.4,'2 (1)','8');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (3,'KeAndre Bates','SO','Florida','7.82',-0.7,'1 (1)','6');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (4,'Corey Crawford','SR','Rutgers','7.69',1.1,'2 (5)','5');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (5,'Adoree Jackson','SO','USC','7.66',1.8,'2 (2)','4');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (6,'Jonathan Addison','SR','North Carolina St.','7.62',-0.3,'2 (6)','3');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (7,'Emmanuel Williams','SR','Northwestern St.','7.59',-2.6,'2 (7)','2');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (8,'Zack Bazile','SO','Ohio State','7.58',-1.2,'2 (3)','1');
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (9,'Andreas Trajkovski','JR','Arkansas','7.58',-1.9,'1 (2)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (10,'Terrell McClain','SO','Akron','7.48',0.4,'1 (3)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (11,'Julian Harvey','JR','SIU-Edwardsville','7.47',-0.7,'1 (4)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (12,'Fred Dorsey','SO','Kentucky','7.47',0.4,'1 (5)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (13,'Steffin McCarter','FR','Texas','7.45',-0.6,'2 (8)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (14,'Charles Brown','FR','Texas Tech','7.43',-0.9,'1 (6)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (15,'Joseph Oduho','JR','Akron','7.41',-0.5,'1 (7)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (16,'Arphaxad Carroll','SO','Idaho','7.40',-1.8,'1 (8)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (17,'Trey McRae','SR','Charlotte','7.39',-0.2,'1 (9)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (18,'Jemal Parharm','SO','UL-Monroe','7.26',-1.4,'2 (9)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (19,'Andre Dorsey','SR','Kennesaw State','7.25',-2.0,'1 (10)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (20,'Kurt Jenner','JR','Arkansas','7.24',0.4,'2 (10)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (21,'Austin Hazel','JR','UCLA','7.20',-1.8,'1 (11)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (22,'Will Williams','SO','Texas A&M','7.17',0.0,'2 (11)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (23,'Allan Hamilton','SR','New Mexico','7.15',-2.5,'1 (12)',null);
insert into m_LJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values (null,'Stefan Brits','SR','Florida State','DNS',0,'2',null);

insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('1','Latario Collie','SR','Texas A&M','16.97','1.4','2 (1)','10');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('2','KeAndre Bates','SO','Florida','16.73','3.2','2 (4)','8');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('3','Matthew Oneal','SR','South Florida','16.59','-0.6','2 (3)','6');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('4','Tim White','JR','Arizona State','16.57','0.7','2 (2)','5');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('5','Shawn Johnson','SR','Auburn','16.28','0.9','2 (6)','4');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('6','Brian Leap','SR','Penn State','16.13','1.4','2 (5)','3');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('7','Lathone Collie','SR','Texas A&M','16.02','-1.8','1 (1)','2');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('8','Kaiwan Culmer','SO','Nebraska','15.93','1.0','1 (2)','1');
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('9','Marcus Ghent','SR','FIU','15.87','1.3','2 (7)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('10','Felix Obi','SR','Baylor','15.86','1.7','2 (8)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('11','John-Patrick Friday','SR','Miami','15.77','2.4','1 (3)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('12','John Warren','SO','Missouri','15.74','1.1','2 (9)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('13','Tony Carodine','SR','Missouri','15.74','1.6','2 (10)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('14','Shane Green','SR','Coppin State','15.69','1.2','1 (4)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('15','Jeffrey Prothro','JR','Texas A&M','15.66','0.6','1 (5)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('16','Ben Williams','JR','Louisville','15.48','1.7','2 (11)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('17','Josh Dixon','SR','Arizona State','15.45','-1.7','1 (6)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('18','Phillip Smith','JR','Mid. Tenn. State','15.22','1.8','1 (7)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('19','Charles Brown','FR','Texas Tech','15.22','1.7','1 (8)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('20','Scotty Newton','SO','TCU','15.19','2.7','1 (9)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('21','Bobby Plummer','JR','Cornell','15.17','1.1','1 (10)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('22','EJ Reddick','SR','Charleston Southern','15.05','3.2','1 (11)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('23','Clive Pullen','JR','Arkansas','15.01','-0.7','2 (12)',null);
insert into m_TJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('24','Donovan Tolbert','SR','Kent State','14.92','-0.8','1 (12)',null);

insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('1','Randall Cunningham','SO','USC','2.25','1 (1)','10');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('2','Christoff Bryan','SO','Kansas State','2.22','1 (2)','8');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('3','Trey McRae','SR','Charlotte','2.19','1 (3)','6');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('4','Avion Jones','SR','East Carolina','2.19','1 (4)','5');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('5','Trey Culver','SO','Texas Tech','2.19','1 (5)','4');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('6','Bradley Adkins','SR','Texas Tech','2.19','1 (6)','3');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('7','Matthew Campbell','JR','Albany','2.19','1 (7)','2');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('8','Kyle Landon','JR','Southern Illinois','2.19','1 (8)','1');
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('8','Keenon Laine','FR','Western Kentucky','2.19','1 (8)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('10','Brett Pozolinski','SR','Wis.-Milwaukee','2.14','1 (10)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('11','Branden Greene','SR','Mississippi','2.14','1 (11)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Ty Anderson','SO','UTSA','2.14','1 (12)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('13','Curtis Richardson','FR','Akron','2.09','1 (13)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('13','Eric Moore','SO','Central Arkansas','2.09','1 (13)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('13','Grant Anderson','SO','Nebraska','2.09','1 (13)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('13','Cody Stine','FR','Akron','2.09','1 (13)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('13','Zachary Blackham','SR','BYU','2.09','1 (13)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('18','Seth Peace','SR','Miss State','2.09','1 (18)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('18','Thilina Karunaratne','FR','Kansas State','2.09','1 (18)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('18','Ken LeGassey','JR','Arkansas','2.09','1 (18)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('18','Jordan Wesner','FR','Memphis','2.09','1 (18)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('22','Andre Dorsey','SR','Kennesaw State','2.09','1 (22)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('22','Justin Fondren','SR','Alabama','2.09','1 (22)',null);
insert into m_HJ_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Xaivier McAllister','JR','Kentucky','NH','1',null);

insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('1','Jake Blankenship','SR','Tennessee','5.60','1 (1)','10');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('2','Torben Laidig','SO','Virginia Tech','5.55','1 (2)','8');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('3','Devin King','SO','SE Louisiana','5.45','1 (3)','6');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('4','Craig Hunter','JR','Connecticut','5.45','1 (4)','5');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('5','Jax Thoirs','SR','Washington','5.45','1 (5)','4');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('6','Dylan Bell','SR','Air Force','5.45','1 (6)','3');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('7','Cole Walsh','SO','Oregon','5.30','1 (7)','2');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('7','Adam Bragg','SR','Princeton','5.30','1 (7)','1');
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('7','Tray Oates','SO','Samford','5.30','1 (7)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('10','Matthew Ludwig','FR','Missouri','5.30','1 (10)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('11','Kyle Pater','JR','Air Force','5.30','1 (11)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Jesse Oxley','SR','Kent State','5.15','1 (12)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Jacob Wooten','FR','Texas A&M','5.15','1 (12)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Brandon Bray','FR','Texas Tech','5.15','1 (12)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Dylan Duvio','JR','Stanford','5.15','1 (12)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('12','Brad Johnson','JR','Virginia Tech','5.15','1 (12)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('17','Barrett Poth','FR','Texas','5.15','1 (17)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('17','Chris Uhle','SR','Virginia Tech','5.15','1 (17)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('17','Reese Watson','SR','Texas','5.15','1 (17)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('20','Matthew Rowland','JR','Akron','5.15','1 (20)',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Adrian Valles','SO','Cincinnati','NH','1',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Deakin Volz','FR','Virginia Tech','NH','1',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Chase Wolfle','SR','Texas A&M','NH','1',null);
insert into m_PV_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Carl Johansson','SO','Texas A&M','NH','1',null);

insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (1,'Nick Miller','SR','Oklahoma State','73.98','2 (2)','10');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (2,'Rudy Winkler','JR','Cornell','72.84','2 (1)','8');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (3,'Greg Skipper','SR','Oregon','71.39','2 (5)','6');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (4,'Sean Donnelly','SR','Minnesota','71.28','2 (3)','5');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (5,'Anders Eriksson','FR','Florida','70.48','2 (4)','4');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (6,'Chukwuebuka Enekwechi','SR','Purdue','69.74','2 (6)','3');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (7,'Adam Keenan','JR','Northern Arizona','69.45','2 (7)','2');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (8,'Dempsey McGuigan','SO','Mississippi','69.23','2 (8)','1');
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (9,'Alex Poursanidis','JR','Georgia','68.83','1 (1)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (10,'Tomas Kruzliak','SR','Virginia Tech','68.32','1 (2)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (11,'Denzel Comenentia','FR','Georgia','68.21','2 (9)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (12,'Elias Hakansson','JR','Alabama','67.11','1 (3)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (13,'Conner Neu','SR','Youngstown State','66.33','1 (4)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (14,'Adam Kelly','FR','Princeton','65.82','1 (5)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (15,'Justin Baker','SR','Northern Iowa','65.76','2 (10)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (16,'Renaldo Frechou','SR','South Alabama','65.66','1 (6)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (17,'Joseph Ellis','FR','Michigan','65.43','2 (11)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (18,'Bradley Sauer','SR','Southern Illinois','64.24','2 (12)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (19,'Austin Riddle','SO','Rice','63.09','1 (7)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (20,'Skylar Arneson','SR','Wichita State','62.89','1 (8)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (21,'Tyler Merkley','FR','Kansas State','62.09','1 (9)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (22,'Brady Grunder','JR','Kansas State','61.68','1 (10)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (23,'Fellan McGuigan','FR','TCU','60.25','1 (11)',null);
insert into m_HT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (24,'Robert Marlow','JR','Long Beach St.','60.21','1 (12)',null);

insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (1,'Nicholas Percy','SO','Nebraska','61.27','2 (1)','10');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (2,'Sam Mattis','SR','Penn','60.96','2 (6)','8');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (3,'Marek Barta','SO','Virginia Tech','60.96','1 (1)','6');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (4,'Gerhard De Beer','JR','Arizona','60.88','2 (4)','5');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (5,'Filip Mihaljevic','JR','Virginia','60.28','2 (5)','4');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (6,'Jan-Louw Kotze','SR','South Alabama','59.79','2 (2)','3');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (7,'Reginald Jagers','JR','Kent State','59.56','2 (3)','2');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (8,'Kevin Farley','SR','SE Missouri','57.90','2 (7)','1');
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (9,'Jayson Kovar','JR','Southern Utah','57.76','1 (2)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (10,'Mitchell Cooper','JR','Kansas','57.39','2 (8)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (11,'Joe Williams','JR','Alabama','57.13','1 (3)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (12,'Jordan Young','JR','Virginia','57.02','1 (4)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (13,'Nicolai Ceban','SO','Kansas','56.74','2 (9)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (14,'Adam Damadzic','JR','TCU','55.18','1 (5)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (15,'David Lucas','FR','Penn State','55.12','2 (10)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (16,'Hayden Reed','JR','Alabama','55.06','1 (6)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (17,'Kord Ferguson','FR','Alabama','54.99','1 (7)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (18,'Nicholas Scarvelis','SR','UCLA','54.50','1 (8)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (19,'Jeff Bartlett','JR','Texas A&M','54.36','2 (11)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (20,'Dotun Ogundeji','FR','UCLA','53.67','1 (9)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (21,'Josh McDonald','SO','Wisconsin','47.57','1 (10)',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Daniel Haugh','FR','Alabama','FOUL','1',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Reno Tuufuli','FR','Iowa','FOUL','1',null);
insert into m_DT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (null,'Phillip Jagers','JR','Akron','FOUL','2',null);

insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (1,'Curtis Thompson','SO','Miss State','77.64','1 (1)','10');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (2,'Ioannis Kyriazis','SO','Texas A&M','77.25','2 (3)','8');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (3,'John Ampomah','SR','Mid. Tenn. State','76.44','2 (1)','6');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (4,'Emron Gibbs','SR','Southern Miss.','74.62','2 (2)','5');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (5,'Evan Karakolis','SR','Rice','73.95','2 (5)','4');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (6,'Jay Stell','SR','Navy','73.81','2 (4)','3');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (7,'Cody Danielson','JR','Oregon','72.92','1 (2)','2');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (8,'Rob Robbins','SR','Cornell','72.52','1 (3)','1');
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (9,'Damien Odle','JR','Wichita State','71.90','2 (6)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (10,'John Nizich','FR','Oregon','70.35','1 (4)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (11,'Tomas Guerra','SR','Western Kentucky','70.34','2 (7)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (12,'Matti Mortimore','JR','North Dakota State','70.30','1 (5)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (13,'Reinhard Van Zyl','JR','Missouri','70.25','1 (6)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (14,'Hudson Keffer','FR','Arizona State','70.23','2 (8)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (15,'Carson Fuller','SR','Washington','70.22','1 (7)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (16,'Tyler Renton','SR','Oklahoma','70.17','2 (9)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (17,'Chris Mirabelli','SO','Rutgers','69.90','1 (8)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (18,'Quinn Hale','SR','Washington','69.55','1 (9)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (19,'Matija Muhar','FR','Virginia Tech','69.53','2 (10)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (20,'Kaleb Zuidema','JR','South Carolina','69.32','1 (10)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (21,'Vincent Rentzsch','SR','UMBC','69.27','2 (11)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (22,'Sam Hardin','SO','Texas A&M','67.86','2 (12)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (23,'Bill Stanley','JR','Ohio State','65.93','1 (11)',null);
insert into m_JT_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (24,'Christian Spaulding','SR','High Point','62.92','1 (12)',null);

insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (1,'Filip Mihaljevic','JR','Virginia','20.71','2 (1)','10');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (2,'Chukwuebuka Enekwechi','SR','Purdue','20.37','2 (3)','8');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (3,'Mostafa Hassan','SO','Colorado St.','20.19','2 (2)','6');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (4,'Nicholas Scarvelis','SR','UCLA','20.17','2 (4)','5');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (5,'Braheme Days','SO','UCLA','20.03','2 (5)','4');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (6,'Josh Freeman','SR','Southern Illinois','19.46','1 (3)','3');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (7,'Josh Awotunde','SO','South Carolina','19.43','1 (1)','2');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (8,'Brett Neelly','FR','Kansas State','19.16','1 (2)','1');
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (9,'Ashinia Miller','SR','Georgia','19.04','2 (6)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (10,'Kevin Farley','SR','SE Missouri','18.83','1 (4)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (11,'Oghenakpobo Efekoro','FR','Virginia','18.82','1 (5)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (12,'Nicholas Ponzio','SO','USC','18.80','2 (7)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (13,'Gian Ragonesi','JR','Miami','18.76','1 (6)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (14,'Alex Renner','JR','North Dakota State','18.74','1 (7)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (15,'Aaron Castle','JR','Arizona','18.74','2 (8)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (16,'Willie Morrison','FR','Indiana','18.69','2 (9)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (17,'Denzel Comenentia','FR','Georgia','18.66','1 (8)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (18,'Ahmed Hassan','SR','Arizona State','18.64','1 (9)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (19,'Peter Simon','SO','California','18.55','1 (10)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (20,'Dotun Ogundeji','FR','UCLA','18.55','2 (10)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (21,'Kyle Felpel','JR','Alabama','18.51','2 (11)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (22,'JC Murasky','SR','Ohio State','18.32','2 (12)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (23,'Isaiah Simmons','JR','Miami','18.23','1 (11)',null);
insert into m_SP_final_2016 (PLACE,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values (24,'Kord Ferguson','FR','Alabama','18.14','1 (12)',null);
