insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'Daniel HAUGH','SR','Kennesaw State','74.63','2 (4)','10');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Gleb DUDAREV','JR','Kansas','73.88','2 (1)','8');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Hilmar ORN JONSSON','SR','Virginia','73.31','2 (2)','6');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'Thomas MARDAL','SO','Florida','73.10','2 (5)','5');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Denzel COMENENTIA','SR','Georgia','72.93','2 (3)','4');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'AJ MCFARLAND','SR','Florida','71.68','2 (7)','3');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Morgan SHIGO','SR','Penn State','70.75','2 (6)','2');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (8,'Joe ELLIS','SR','Michigan','69.26','1 (1)','1');
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Silviu BOCANCEA','SR','California','68.50','2 (8)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (10,'Kevin ARREAGA','JR','Miami','68.32','1 (2)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'Anders ERIKSSON','SR','Florida','68.14','1 (3)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Brock EAGER','SR','Washington St.','67.69','2 (9)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Georgios KORAKIDIS','SO','Tennessee','67.65','1 (4)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (14,'Kieran MCKEAG','SO','Minnesota','67.60','1 (5)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Justin STAFFORD','SR','UCLA','67.05','1 (6)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (16,'Bobby COLANTONIO','FR','Alabama','66.47','1 (7)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Vlad PAVLENKO','SR','Iowa State','66.39','1 (8)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (18,'Nathan BULTMAN','SR','USC','65.80','2 (10)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Alexios PRODANAS','JR','UMBC','65.66','1 (9)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Erick LOOMIS','SR','Cal St. Northridge','65.57','2 (11)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Erich SULLINS','SR','Arkansas','65.47','2 (12)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (22,'Alex TALLEY','SO','North Dakota State','65.47','1 (10)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (23,'Max LYDUM','JR','Oregon','61.26','1 (11)',null);
insert into m_HT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (24,'Logan BLOMQUIST','JR','SE Missouri','60.45','1 (12)',null);

insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'Chris NILSEN','JR','South Dakota','5.95','1 (1)','10');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Mondo DUPLANTIS','FR','LSU','5.80','1 (2)','8');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Clayton FRITSCH','SO','Sam Houston St.','5.75','1 (3)','6');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'KC LIGHTFOOT','FR','Baylor','5.70','1 (4)','5');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Michael CARR','SR','Arkansas State','5.70','1 (5)','4');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'Zach BRADFORD','FR','Kansas','5.70','1 (6)','3');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Brandon BRAY','JR','Texas Tech','5.70','1 (7)','2');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (8,'Drew MCMICHAEL','SR','Texas Tech','5.60','1 (8)','1');
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Sondre GUTTORMSEN','FR','UCLA','5.60','1 (9)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (10,'Adam COULON','JR','Indiana','5.50','1 (10)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'Deakin VOLZ','SR','Virginia Tech','5.50','1 (11)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'Branson ELLIS','FR','Stephen F. Austin','5.50','1 (11)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Matthew LUDWIG','SR','Akron','5.35','1 (13)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Sean CLARKE','JR','Penn','5.35','1 (13)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Chase SMITH','JR','Washington','5.35','1 (15)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Christian CHAMPEN','JR','Kent State','5.35','1 (15)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Jacob WOOTEN','SR','Texas A&M','5.35','1 (15)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (18,'Cole COURTOIS','SO','Louisiana Tech','5.35','1 (18)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Erick DUFFY','SO','Harvard','5.20','1 (19)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Carl JOHANSSON','SR','Texas A&M','5.20','1 (19)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Matthew PEARE','SO','Kentucky','5.20','1 (21)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Brock MAMMOSER','SO','Indiana','5.20','1 (21)',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (null,'Sean COLLINS','SR','South Alabama','NH','1',null);
insert into m_PV_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (null,'Matthew KEIM','JR','Akron',null,'1',null);

insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'Anderson PETERS','SO','Miss State','86.62','2 (1)','10');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Curtis THOMPSON','SR','Miss State','78.43','2 (2)','8');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Tyriq HORSFORD','FR','Miss State','75.59','2 (3)','6');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'Sindri GUDMUNDSSON','JR','Utah State','73.92','2 (4)','5');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Aaron TRUE','SR','Wichita State','73.11','2 (5)','4');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'Sam HARDIN','SR','Texas A&M','73.05','1 (1)','3');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Ethan DABBS','FR','Virginia','72.23','2 (6)','2');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (8,'Denham PATRICELLI','SR','Washington','70.98','2 (7)','1');
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Chris MIRABELLI','SR','Rutgers','69.71','1 (2)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (10,'John NIZICH','SR','Oregon','69.43','2 (8)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'William PETERSSON','JR','Texas A&M','69.20','1 (3)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Werner BOUWER','JR','Texas Tech','69.19','2 (9)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Mark PORTER','SO','Penn State','68.31','2 (10)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (14,'Denzel PRATT','SR','Liberty','67.40','2 (11)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Trevor DANIELSON','SR','Texas','66.84','2 (12)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (16,'Skyler PORCARO','SR','Southern Utah','66.68','1 (4)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Marc MINICHELLO','FR','Penn','66.67','1 (5)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (18,'Jackson VAN VUREN','JR','Oregon','66.00','1 (6)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'August COOK','SO','Army West Point','65.82','1 (7)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Hayden FOX','FR','Navy','64.60','1 (8)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Cade ANTONUCCI','SO','Auburn','63.89','1 (9)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (22,'Simon LITZELL','JR','UCLA','63.41','1 (10)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (23,'Elijah MARTA','SR','Kentucky','61.40','1 (11)',null);
insert into m_JT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (24,'Brendan ARTLEY','FR','North Dakota State','59.57','1 (12)',null);

insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (1,'JuVaughn HARRISON','SO','LSU','8.20','0.7','2 (1)','10');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (2,'Trumaine JEFFERSON','SR','Houston','8.18','1.6','2 (2)','8');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (3,'Yann RANDRIANASOLO','SR','South Carolina','8.12','2.3','2 (3)','6');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (4,'Justin HALL','JR','Texas Tech','8.05','0.7','2 (4)','5');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (5,'Jacob FINCHAM-DUKES','SR','Oklahoma State','8.00','2.0','2 (5)','4');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (6,'Jamie BROWN','SR','Alabama State','7.88','1.8','2 (6)','3');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (7,'Kemonie BRIGGS','SR','Long Beach St.','7.87','2.1','1 (1)','2');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (8,'Jordan LATIMER','SR','Akron','7.83','3.2','2 (7)','1');
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (9,'Odaine LEWIS','SR','Texas Tech','7.78','2.1','1 (2)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (10,'Steffin MCCARTER','JR','Texas','7.76','1.3','2 (8)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (11,'Chris MCBRIDE','SR','Clemson','7.73','1.0','1 (3)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (12,'Grant HOLLOWAY','JR','Florida','7.72','1.3','1 (4)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (13,'Charles BROWN','SR','Texas Tech','7.70','3.1','2 (9)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (14,'Carter SHELL','SO','Arkansas State','7.67','2.8','1 (5)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (15,'Samory FRAGA','SR','Kent State','7.65','2.7','1 (6)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (16,'RnullLazon BRUMFIELD','SO','Tennessee St.','7.62','1.6','1 (7)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (17,'Allen GORDON','SO','Ole Miss','7.61','1.4','1 (8)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (18,'Kenan JONES','FR','LSU','7.54','1.7','2 (10)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (19,'Jullane WALKER','JR','Kansas State','7.44','2.0','2 (11)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (20,'DaJuan SEWARD','SR','Ohio State','7.38','2.6','1 (9)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (21,'Rayvon GREY','JR','LSU','7.38','1.6','2 (12)',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (null,'Keshun MCGEE','JR','Eastern Washington','FOUL',null,'1',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (null,'Jalen SEALS','SO','Baylor','DNS',null,'1',null);
insert into m_LJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (null,'Derrick MONROE','SR','Arizona State','DNS',null,'1',null);

insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (1,'Chengetayi MAPAYA','SO','TCU','17.13','1.1','2 (1)','10');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (2,'Jordan SCOTT','JR','Virginia','17.01','1.0','2 (7)','8');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (3,'Armani WALLACE','SR','Florida State','16.99','1.1','2 (5)','6');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (4,'John WARREN','SR','Southern Miss','16.78','1.2','2 (4)','5');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (5,'OnullBrien WASOME','JR','Texas','16.71','2.6','2 (2)','4');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (6,'Odaine LEWIS','SR','Texas Tech','16.70','1.4','2 (3)','3');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (7,'Eric BETHEA','SR','Indiana','16.65','0.9','1 (1)','2');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (8,'Tuomas KAUKOLAHTI','JR','California','16.50','0.9','2 (6)','1');
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (9,'Adenull MASON','JR','Oklahoma','16.38','1.2','1 (2)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (10,'Treyvon FERGUSON','FR','Kansas','16.18','2.0','1 (3)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (11,'RnullLazon BRUMFIELD','SO','Tennessee St.','16.14','1.4','2 (8)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (12,'Jah STRANGE','JR','Purdue','16.03','1.1','2 (9)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (13,'Clayton BROWN','JR','Florida','15.99','1.6','1 (4)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (14,'Papay GLAYWULU','SO','Oklahoma','15.94','0.8','2 (10)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (15,'Christian MILLER','JR','LSU','15.94','1.0','1 (5)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (16,'Charles BROWN','SR','Texas Tech','15.87','1.1','1 (6)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (17,'Devon WILLIS','SR','Albany','15.83','1.4','1 (7)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (18,'Keshun MCGEE','JR','Eastern Washington','15.77','1.1','2 (11)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (19,'Tamar GREENE','SO','Purdue','15.64','0.9','2 (12)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (20,'Jaden PURNELL','SR','Oral Roberts','15.63','1.0','1 (8)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (21,'Rickey FANTROY','JR','BYU','15.49','1.1','1 (9)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (22,'Georgi NACHEV','FR','Missouri','15.37','1.1','1 (10)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (23,'Jamar DAVIS','FR','NC State','15.28','0.6','1 (11)',null);
insert into m_TJ_final_2019 (Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values (24,'Daniel IGBOKWE','JR','Columbia','15.14','1.1','1 (12)',null);

insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'Adrian PIPERI','SO','Texas','21.11','2 (1)','10');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Denzel COMENENTIA','SR','Georgia','20.77','2 (2)','8');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Jordan GEIST','SO','Arizona','20.31','2 (3)','6');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'Payton OTTERDAHL','SR','North Dakota State','19.89','2 (4)','5');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Dotun OGUNDEJI','SR','UCLA','19.73','2 (5)','4');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'Matthew KATNIK','SR','USC','19.65','1 (1)','3');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Nate ESPARZA','SO','UCLA','19.65','1 (2)','2');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (8,'Andrew LISKOWITZ','JR','Michigan','19.52','2 (6)','1');
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Joseph MAXWELL','SO','Tennessee','19.50','2 (7)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (10,'Otito OGBONNIA','FR','UCLA','19.44','1 (3)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'Connor BANDEL','SO','Florida','19.30','2 (8)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Oghenakpobo EFEKORO','SR','Virginia','19.16','1 (4)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Corey MURPHY','SR','Monmouth','19.14','2 (9)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (14,'Burger LAMBRECHTS JR.','SO','Nebraska','18.91','1 (5)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Kristoffer THOMSEN','FR','North Dakota State','18.90','2 (10)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (16,'Jonah WILSON','SO','Washington','18.82','1 (6)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Kord FERGUSON','SR','Alabama','18.81','1 (7)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (18,'Eric FAVORS','JR','South Carolina','18.57','1 (8)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Alex TALLEY','SO','North Dakota State','18.49','2 (11)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Isaiah ROGERS','JR','Virginia Tech','18.28','1 (9)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Santiago BASSO','FR','Alabama','18.11','1 (10)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (22,'Chance EHRNSBERGER','SO','Ohio State','17.98','1 (11)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (23,'Darius KING','JR','Northern Iowa','16.90','1 (12)',null);
insert into m_SP_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (null,'Noah CASTLE','SR','Kentucky','FOUL','2',null);

insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'JuVaughn HARRISON','SO','LSU','2.27','1 (1)','10');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Tejaswin SHANKAR','SO','Kansas State','2.27','1 (2)','8');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Shelby MCEWEN','JR','Alabama','2.24','1 (3)','6');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'Keenon LAINE','SR','Georgia','2.24','1 (4)','5');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Eric RICHARDS','JR','Southern Miss','2.24','1 (5)','4');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'Sean LEE','FR','UCLA','2.21','1 (6)','3');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Frank HARRIS','SO','Southern Utah','2.21','1 (7)','1.5');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Darius CARBIN','JR','Georgia','2.21','1 (7)','1.5');
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Roberto VILCHES','FR','Missouri','2.18','1 (9)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Jhonny VICTOR','SR','Florida','2.18','1 (9)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Cody STINE','JR','Ohio State','2.18','1 (9)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Earnie SEARS','SO','USC','2.18','1 (12)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Mayson CONNER','FR','Nebraska','2.18','1 (12)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Justice SUMMERSET','JR','Arizona','2.18','1 (12)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Rahman MINOR','SO','Kentucky','2.18','1 (15)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (16,'Brenton FOSTER','JR','Virginia','2.18','1 (16)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Zack ANDERSON','JR','South Dakota','2.15','1 (17)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Jyles ETIENNE','SO','Indiana','2.15','1 (17)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Mitch JACOBSON','SO','Washington St.','2.15','1 (19)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Curtis RICHARDSON','SR','Akron','2.10','1 (20)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Jake BENNINGHOFF','SO','Texas Tech','2.10','1 (20)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Jay HUNT','SO','Iowa','2.10','1 (20)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (23,'Peyton FREDRICKSON','SR','Washington St.','2.10','1 (23)',null);
insert into m_HJ_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (24,'Jacob PATTEN','SR','Mid. Tenn. State',null,'1 (24)',null);

insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (1,'Eric KICINSKI','SR','Texas Tech','62.53','2 (3)','10');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (2,'Payton OTTERDAHL','SR','North Dakota State','62.48','2 (1)','8');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (3,'Kord FERGUSON','SR','Alabama','62.07','2 (2)','6');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (4,'Dotun OGUNDEJI','SR','UCLA','60.35','2 (6)','5');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (5,'Denzel COMENENTIA','SR','Georgia','59.97','2 (5)','4');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (6,'Samuel WELSH','FR','Harvard','59.54','2 (4)','3');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (7,'Elijah MASON','FR','Washington','58.29','2 (7)','2');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (8,'Brett NEELLY','SR','Kansas State','58.23','1 (1)','1');
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (9,'Jerimiah EVANS','SO','Michigan State','57.85','1 (2)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (10,'Nathan DUNIVAN','SR','Weber State','57.75','1 (3)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (11,'Ben HAMMER','SR','South Dakota','57.66','1 (4)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (12,'Greg THOMPSON','SR','Maryland','57.37','2 (8)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (13,'Roje STONA','FR','Clemson','57.29','2 (9)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (14,'Michael RENARD','JR','Army West Point','57.28','1 (5)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (15,'Charles LENFORD JR.','JR','Kentucky','56.86','2 (10)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (16,'Carlos DAVIS','SR','Nebraska','56.51','2 (11)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (17,'Adam DAWSON','FR','Colorado St.','55.16','1 (6)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (18,'Iffy JOYNER','SO','California','55.16','2 (12)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (19,'Noah CASTLE','SR','Kentucky','54.63','1 (7)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (20,'Jonah WILSON','SO','Washington','54.50','1 (8)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (21,'Grant VOEKS','JR','Clemson','54.25','1 (9)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (22,'Adar SHEERE','FR','Memphis','53.30','1 (10)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (23,'Khalil DAVIS','SR','Nebraska','51.39','1 (11)',null);
insert into m_DT_final_2019 (Place,Name,YEAR,TEAM,Mark,"Flight(pl)",Score) values (24,'Kelly COOK JR.',null,'William and Mary','51.30','1 (12)',null);
