insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'Thomas MARDAL','Florida','SR','76.74','2 (1)','10');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'Gleb DUDAREV','Kansas','SR','74.53','2 (2)','8');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Kostas ZALTOS','Minnesota','FR','71.21','2 (3)','6');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Vlad PAVLENKO','Iowa State','SR','71.12','1 (1)','5');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Alexios PRODANAS','Virginia Tech','SR','71.08','2 (4)','4');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (6,'Alex TALLEY','North Dakota State','JR','70.99','2 (6)','3');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Jon NERDAL','LSU','SR','70.88','1 (2)','2');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Jordan GEIST','Arizona','JR','70.53','2 (5)','1');
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (9,'Tyler MERKLEY','Penn State','SO','70.28','2 (7)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Manning PLATER','Illinois','SR','70.15','1 (3)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Nathan BULTMAN','USC','SR','70.09','2 (8)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (12,'Michael BRYAN','Wichita State','JR','70.08','1 (4)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Israel OLOYEDE','Arizona','JR','69.99','2 (9)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (14,'Kevin ARREAGA','Miami (Fla.)','SR','69.60','2 (10)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (15,'Bobby COLANTONIO','Alabama','SO','69.53','1 (5)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (16,'Georgios KORAKIDIS','Tennessee','JR','69.45','1 (6)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (17,'Ricky HURLEY','Southern Illinois','SR','68.82','1 (7)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (18,'Ryan DAVIS','East Carolina','SR','68.79','1 (8)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Kieran MCKEAG','Alabama','SR','68.43','2 (11)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (20,'Alencar PEREIRA','Georgia','SO','67.83','2 (12)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (21,'Taige BRYANT','Eastern Michigan','SR','67.43','1 (9)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (22,'Jake NORRIS','LSU','JR','67.12','1 (10)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (23,'Bayley CAMPBELL','Oklahoma','SO','65.86','1 (11)',null);
insert into m_HT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (24,'Jayden WHITE','Washington','FR','63.04','1 (12)',null);

insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'Branson ELLIS','Stephen F. Austin','SO','5.70',null,'10');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'Keaton DANIEL','Kentucky','FR','5.55',null,'8');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Ethan BRAY','South Dakota','SR','5.55',null,'6');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Clayton FRITSCH','Sam Houston','JR','5.55',null,'5');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Zach BRADFORD','Kansas','SO','5.45',null,'4');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (6,'Ryan LIPE','Alabama','JR','5.45',null,'3');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Paulo BENAVIDES','UTEP','SR','5.30',null,'2');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Hussain AL HIZAM','Kansas','SR','5.30',null,'1');
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (9,'Zach MCWHORTER','BYU','FR','5.30',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Jack RHEA','Kennesaw State','SR','5.30',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Kyle RADEMEYER','South Alabama','FR','5.30',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Christyan SAMPY','Houston','SO','5.30',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Nathan STONE','Indiana','FR','5.15',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Trevor STEPHENSON','Michigan State','JR','5.15',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Cole Courtois','UL-Lafayette','JR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Trent Francom','South Dakota St.','JR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Antonio Ruiz','Houston','JR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Stone Baker','South Florida','SO','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Sam Young','Virginia','SR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Marshall Faurot','South Dakota','FR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Travis Snyder','Connecticut','SO','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Michael Gonzalez','North Texas','SR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Cole Colozzo','Ole Miss','SR','NH',null,null);
insert into m_PV_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Elijah Cole','Charlotte','SR','NH',null,null);

insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'Tzuriel PEDIGO','LSU','FR','76.98','2 (4)','10');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'DJ JONSSON','Miss State','FR','76.73','2 (1)','8');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Cade ANTONUCCI','Auburn','SR','76.14','1 (2)','6');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Tyriq HORSFORD','Miss State','SO','75.95','2 (2)','5');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Sindri GUDMUNDSSON','Miss State','SR','75.61','2 (5)','4');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (6,'Franck DISANZA','SE Louisiana','FR','74.71','1 (1)','3');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Cameron BATES','BYU','SO','74.25','2 (3)','2');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Benji PHILLIPS','North Dakota State','SO','71.40','2 (7)','1');
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (9,'Scott FUCHS','Iowa State','SR','70.91','2 (6)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Nils FISCHER','Auburn','SR','69.69','2 (8)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Arthur PETERSEN','UT-Arlington','FR','69.69','1 (3)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (12,'Mark PORTER','Penn State','JR','69.19','1 (4)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'August COOK','Army West Point','SR','68.48','2 (9)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (14,'Donavon BANKS','McNeese State','SR','68.07','1 (5)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (15,'Logan WOLFLEY','Kansas State','SR','67.59','2 (10)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (16,'Chase TARR','UC Santa Barbara','SO','67.00','1 (6)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (17,'Cord NEAL','Stephen F. Austin','JR','65.86','2 (11)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (18,'Sam HANKINS','Texas A&M','FR','64.96','1 (7)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Carlan NAISANT','Arizona State','SO','64.83','1 (8)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (20,'James MCNANEY','Rice','JR','63.96','2 (12)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (21,'Dalton RASMUSSEN','Oregon','SO','62.81','1 (9)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (22,'Izac CANCHOLA','Stephen F. Austin','FR','62.44','1 (10)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (23,'Hunter LONGINO','McNeese State','FR','57.00','1 (11)',null);
insert into m_JT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (24,'Brian SAGENDORF','Mount St. Mary''s','SR','54.23','1 (12)',null);

insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (1,'JuVaughn HARRISON','LSU','JR','8.27','1.9','1 (1)','10');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (2,'Isaac GRIMES','Florida State','JR','8.05','0.4','1 (2)','8');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (3,'Carey MCLEOD','Tennessee','JR','7.94','0.2','1 (3)','6');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (4,'Brandon HICKLIN','N. Carolina A&T','JR','7.91','1.9','2 (1)','5');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (5,'Steffin MCCARTER','Texas','SR','7.84','-0.2','1 (4)','4');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (6,'Harrison SCHRAGE','UCLA','SR','7.83','0.7','1 (5)','3');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (7,'Rayvon GREY','LSU','SR','7.78','1.1','2 (2)','2');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (8,'Rayvon ALLEN','Oklahoma','JR','7.69','0.6','1 (6)','1');
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (9,'Jason SMITH','Long Beach St.','SR','7.68','1.2','1 (7)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (10,'James CARTER','Iowa','SO','7.65','2.4','2 (3)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (11,'Allen GORDON','Ole Miss','JR','7.64','1.9','1 (8)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (12,'A''Nan BRIDGETT','Rutgers','SO','7.58','1.1','1 (9)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (13,'Cameron CRUMP','Miss State','SO','7.53','1.3','2 (4)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (14,'O''Brien WASOME','Texas','SR','7.49','-0.2','2 (5)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (15,'Jonathan WELLS','Illinois','SR','7.46','1.6','1 (10)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (16,'Ronnie BRISCOE JR.','Texas ','tate','7.46','1.9','2 (6)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (17,'Safir SCOTT','Connecticut','JR','7.40','0.9','1 (11)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (18,'Jullane WALKER','Kansas State','SR','7.34','1.5','2 (7)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (19,'Kenneth PREE','Texas Southern','SO','7.33','0.3','2 (8)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (20,'Michael HOFFER','Nebraska','JR','7.28','0.6','1 (12)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (21,'David EJUMETA','Coastal Carolina','JR','7.27','0.2','2 (9)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (22,'Anthony RILEY','Tennessee','FR','7.22','2.6','2 (10)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (23,'Benjamin OKAFOR','Houston','SO','7.18','1.1','2 (11)',null);
insert into m_LJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (24,'Trey CAUSEY III','Kentucky','SO','6.92','0.5','2 (12)',null);

insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'Turner WASHINGTON','Arizona State','SO','21.10','1 (1)','10');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'Adrian PIPERI','Texas','JR','20.71','1 (3)','8');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Jordan GEIST','Arizona','JR','20.40','1 (4)','6');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Andrew LISKOWITZ','Michigan','SR','20.07','1 (2)','5');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Josh SOBOTA','Kentucky','SO','19.82','2 (2)','4');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (6,'Zack SHORT','Idaho','SR','19.71','1 (5)','3');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Darius KING','Northern Iowa','JR','19.69','1 (6)','2');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Jonah WILSON','Washington','SR','19.67','2 (1)','1');
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (9,'Matthew KATNIK','USC','SR','19.55','2 (3)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Connor BANDEL','Florida','SR','19.13','1 (7)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'McKay JOHNSON','USC','SR','19.09','2 (4)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (12,'Isaac ODUGBESAN','Alabama','JR','18.96','1 (8)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Jordan WEST','Tennessee','SO','18.72','1 (9)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (14,'Kyle MITCHELL','Liberty','JR','18.63','1 (10)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (15,'Santiago BASSO','Alabama','JR','18.59','2 (5)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (16,'John MEYER','Michigan','FR','18.37','1 (11)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (17,'Adam KESSLER','Drake','SR','18.34','1 (12)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (18,'Daniel MCARTHUR','North Carolina','SR','18.06','2 (6)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Charles LENFORD JR.','Kentucky','SR','18.05','2 (7)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (20,'Kristoffer THOMSEN','North Dakota State','SO','18.03','2 (8)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (21,'Kyle ATKINSON','Minnesota','FR','17.45','2 (9)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (22,'Michael SHOAF','Notre Dame','FR','17.35','2 (10)',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Burger LAMBRECHTS JR.','Nebraska','JR','FOUL','2',null);
insert into m_SP_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Eric Favors','South Carolina','SR','DNS','2',null);

insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'JuVaughn HARRISON','LSU','JR','2.33',null,'10');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'Tejaswin SHANKAR','Kansas State','JR','2.23',null,'8');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Mayson CONNER','Nebraska','JR','2.23',null,'6');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Darryl SULLIVAN','Tennessee','SR','2.23',null,'5');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Clayton BROWN','Florida','SR','2.20',null,'3.5');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Vernon TURNER','Oklahoma','SO','2.20',null,'3.5');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Earnie SEARS','USC','SR','2.20',null,'2');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Brandon BURKE','Buffalo','JR','2.20',null,'0.5');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Jordan WESNER','Florida State','SR','2.20',null,'0.5');
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Jason SMITH','Long Beach St.','SR','2.20',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Justice SUMMERSET','Arizona','SR','2.20',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (12,'Zack ANDERSON','South Dakota','SR','2.20',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Bryson DEBERRY','UT-Arlington','JR','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (14,'Allen GORDON','Ole Miss','JR','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (15,'Justin STUCKEY','Samford','SO','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (16,'Dennis MANYEAH','La Salle','SR','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (17,'Ethan HARRIS','Grand Canyon','SR','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (18,'Kaithon MCDONALD','Maryland','JR','2.15',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Eric RICHARDS','Southern Miss.','SR','2.10',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Isaiah HOLMES','Miami (Fla.)','JR','2.10',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (21,'Jonathan WELLS','Illinois','SR','2.10',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Michael Hoffer','Nebraska','JR','NH',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Trey Allen','Louisville','FR','NH',null,null);
insert into m_HJ_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Mitch Jacobson','Washington St.','JR','NH',null,null);

insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (1,'Turner WASHINGTON','Arizona State','SO','63.42','2 (1)','10');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (2,'Roje STONA','Clemson','SO','61.94','2 (2)','8');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (3,'Claudio ROMERO','Virginia','FR','61.36','2 (3)','6');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (4,'Malik PAUL','South Carolina','SR','58.35','1 (1)','5');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (5,'Jacob LEMMON','Virginia','FR','57.78','1 (2)','4');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (6,'Elijah MASON','Washington','JR','57.72','2 (4)','3');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (7,'Colton PALLER','Wyoming','JR','56.86','1 (3)','2');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (8,'Terrell ADAMS','Charlotte','SR','56.85','2 (5)','1');
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (9,'Josh SOBOTA','Kentucky','SO','56.36','1 (4)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (10,'Ian SCHULZ','Arizona State','SO','56.25','1 (5)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (11,'Francois PRINSLOO','South Alabama','FR','56.22','2 (6)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (12,'Adam DAWSON','Colorado St.','JR','56.06','1 (6)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (13,'Iffy JOYNER','California','SO','55.72','2 (7)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (14,'David LUCAS','Penn State','SR','55.53','2 (8)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (15,'Dallin SHURTS','BYU','FR','54.49','1 (7)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (16,'Charles LENFORD JR.','Kentucky','SR','54.45','1 (8)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (17,'Aleks HRISTOV','UTEP','FR','54.32','2 (9)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (18,'Kaleb SIEKMEIER','Minnesota','SO','54.29','1 (9)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (19,'Phillipe BARNETT','Minnesota','SO','53.03','2 (10)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (20,'Adar SHEERE','Louisville','SO','52.22','1 (10)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (21,'Milton INGRAHAM','Florida State','FR','52.17','2 (11)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (22,'Eron CARTER','Arkansas State','JR','52.03','1 (11)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (23,'Mitchell WEBER','Missouri','FR','51.10','2 (12)',null);
insert into m_DT_final_2021 (Place,Name,Team,Year,Mark,"Flight(pl)",Score) values (null,'Taige BRYANT','Eastern Michigan','SR','FOUL','1',null);

insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (1,'Emmanuel IHEMEJE','Oregon','FR','17.14','1.8','1 (1)','10');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (2,'Jah-Nhai PERINCHIEF','Tennessee','SR','17.03','1.2','2 (1)','8');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (3,'Chengetayi MAPAYA','TCU','JR','16.74','0.1','1 (2)','6');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (4,'Sean DIXON-BODIE','LSU','FR','16.61','0.7','1 (3)','5');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (5,'Clayton BROWN','Florida','SR','16.56','-0.4','2 (2)','4');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (6,'Isaiah GRIFFITH','Oregon','SR','16.54','0.3','1 (4)','3');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (7,'Carey MCLEOD','Tennessee','JR','16.40','1.6','1 (7)','2');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (8,'O''Brien WASOME','Texas','SR','16.35','1','1 (5)','1');
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (9,'Georgi NACHEV','Missouri','SO','16.24','0.8','1 (6)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (10,'Jalen SEALS','Texas Tech','JR','16.17','1.1','2 (3)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (11,'Christian EDWARDS','Alabama','JR','16.15','-0.2','1 (8)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (12,'Jordan SCOTT','USC','SR','15.95','-0.5','1 (9)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (13,'Tamar GREENE','Purdue','JR','15.85','-0.5','2 (4)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (14,'R''Lazon BRUMFIELD','Tennessee St.','SR','15.79','0.3','1 (10)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (15,'Owayne OWENS','Virginia','SO','15.77','0.6','2 (5)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (16,'Jalyn JACKSON','USC','JR','15.73','-1.5','2 (6)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (17,'Laquan NAIRN','Arkansas','SR','15.72','2.1','2 (7)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (17,'Jelaani DAVIS','Oklahoma','SO','15.72','2.2','2 (7)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (19,'Tylen GUIDRY','Lamar','SR','15.70','2.3','2 (9)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (20,'Jacore IRVING','Florida State','JR','15.58','1.8','2 (10)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (21,'Chauncey CHAMBERS','Virginia Tech','JR','15.54','1.1','2 (11)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (22,'Safin WILLS','Texas Tech','FR','15.54','0.3','2 (12)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (23,'Keshun MCGEE','Alabama','SR','15.34','1.1','1 (11)',null);
insert into m_TJ_final_2021 (Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values (24,'Keshun BYRD','Miss State','SO','15.33','-0.6','1 (12)',null);
