
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,1,'Logan BLOMQUIST','SE Missouri','SR','73.37','2 (6)','10');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,2,'Tyler MERKLEY','Penn State','JR','72.70','2 (2)','8');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,3,'Kostas ZALTOS','Minnesota','SO','72.51','2 (1)','6');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,4,'Bobby COLANTONIO','Alabama','JR','71.97','2 (5)','5');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,5,'Michael BRYAN','Wichita State','SR','71.56','2 (3)','4');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,6,'Alexander TALLEY','Nebraska','SR','71.52','2 (4)','3');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,7,'Decio ANDRADE','Miami (Fla.)','JR','70.86','2 (7)','2');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,8,'Trey KNIGHT','USC','SO','70.73','1 (2)','1');
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,9,'Jayden WHITE','Washington','FR','69.99','1 (1)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,10,'Jake NORRIS','LSU','SR','69.65','1 (3)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,11,'Bayley CAMPBELL','Oklahoma','JR','68.71','2 (8)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,12,'Edward JEANS','Oklahoma','SR','68.10','1 (4)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,13,'Kade MCCALL','Kansas State','SO','67.71','1 (5)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,14,'Alencar PEREIRA','Georgia','JR','67.66','2 (9)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,15,'James JOYCEY','North Carolina','JR','67.43','2 (10)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,16,'Sean MOCKLER','Indiana','FR','67.20','1 (6)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,17,'Khalil BEDOUI','Virginia Tech','SO','66.76','1 (7)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,18,'Kelly COOK JR.','Purdue','SR','66.64','1 (8)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,19,'Kyle BROWN','Auburn','SO','66.59','1 (9)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,20,'Ivar MOISANDER','California','SO','65.70','1 (10)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,21,'Anthony BARMES','Drake','FR','65.57','2 (11)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,22,'Evan STORK','Sacramento St.','SR','65.56','1 (11)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,23,'Robert WATSON','Memphis','SR','65.24','1 (12)',null);
insert into m_HT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HT',2022,null,'Noah WALKER','Pittsburgh','SR','X','2',null);

insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,1,'Sondre GUTTORMSEN','Princeton','JR','5.75','1 (1)','10');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,2,'Clayton FRITSCH','Sam Houston','SR','5.70','1 (2)','8');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,3,'Keaton DANIEL','Kentucky','SO','5.65','1 (3)','6');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,4,'Simen GUTTORMSEN','Princeton','JR','5.65','1 (4)','5');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,5,'Branson ELLIS','Stephen F. Austin','JR','5.65','1 (5)','4');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,6,'Zach MCWHORTER','BYU','SO','5.60','1 (6)','3');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,7,'Clayton SIMMS','Kansas','FR','5.50','1 (7)','2');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,8,'Kyle RADEMEYER','South Alabama','SO','5.50','1 (8)','1');
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,9,'Zach BRADFORD','Kansas','JR','5.50','1 (9)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,10,'Trevor STEPHENSON','Michigan State','JR','5.45','1 (10)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,11,'Caleb WITSKEN','BYU','JR','5.45','1 (11)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,12,'Antonio RUIZ','Houston','SR','5.40','1 (12)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,13,'Eerik HAAMER','South Dakota','SO','5.40','1 (13)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,14,'Cole RIDDLE','Memphis','SR','5.30','1 (14)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,14,'Robert OSWALD','Ohio State','SR','5.30','1 (14)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,16,'Sean ROTH','Louisville','SR','5.30','1 (16)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,17,'Jacob ENGLAR','Washington St.','JR','5.30','1 (17)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,18,'Alexander SLINKMAN','Rice','SO','5.30','1 (18)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,18,'Erick DUFFY','Duke','SR','5.30','1 (18)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,20,'Colby WILSON','Montana State','SO','5.15','1 (20)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,21,'Max MANSON','Stanford','SO','5.15','1 (21)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,22,'Wyatt LEFKER','Youngstown St.','JR','5.00','1 (22)',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,null,'Hunter Garretson','Akron','SO','NH','1',null);
insert into m_PV_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('PV',2022,null,'James Courson','Auburn','JR','NH','1',null);

insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,1,'Marc MINICHELLO','Penn','SO','81.17','2 (1)','10');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,2,'Ethan DABBS','Virginia','JR','79.68','2 (3)','8');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,3,'Tzuriel PEDIGO','LSU','SO','78.90','2 (5)','6');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,4,'Taran TAYLOR','Wichita State','JR','78.76','2 (8)','5');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,5,'Chinecherem Prosper NNAMDI','Baylor','FR','78.61','2 (2)','4');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,6,'Arthur PETERSEN','UT-Arlington','SO','76.34','2 (4)','3');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,7,'DJ JONSSON','Miss State','SO','76.29','2 (6)','2');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,8,'Ahmed MAGOUR','Georgia','JR','73.14','2 (7)','1');
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,9,'Markim FELIX','Texas Tech','SR','72.30','2 (9)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,10,'Ty HAMPTON','Oregon','FR','72.12','2 (10)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,11,'Evan NIEDROWSKI','Monmouth','FR','70.22','1 (1)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,12,'Eli GAUGHAN','LSU','JR','69.53','1 (2)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,13,'Cord NEAL','Stephen F. Austin','SR','68.62','1 (3)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,14,'Jackson MORRIS','Colorado St.','SO','68.03','1 (4)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,15,'Ashton DOMINGUE','Samford','SO','67.98','1 (5)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,16,'Mark PORTER','Florida','SR','67.93','1 (6)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,17,'Marten GASPARINI','Grand Canyon','SO','67.51','2 (11)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,18,'Braden PRESSER','Navy','SO','67.21','2 (12)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,19,'Roan ALLEN','Washington','JR','66.46','1 (7)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,20,'Michael WHITTAKER','BYU','JR','65.96','1 (8)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,21,'Jared O''RILEY','Arizona','SO','65.42','1 (9)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,22,'Scott CAMPBELL','Duke','SO','65.02','1 (10)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,23,'James MCNANEY','Rice','SR','64.60','1 (11)',null);
insert into m_JT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('JT',2022,24,'Luke JACKSON','Duke','JR','63.89','1 (12)',null);

insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,1,'Adrian PIPERI','Texas','SR','21.52','1 (1)','10');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,2,'Turner WASHINGTON','Arizona State','JR','21.05','2 (1)','8');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,3,'Isaac ODUGBESAN','Alabama','SR','20.48','1 (2)','6');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,4,'Jordan WEST','Tennessee','JR','20.28','1 (5)','5');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,5,'Darius KING','Northern Iowa','SR','20.04','1 (3)','4');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,6,'Logan CALVIN','Illinois State','SR','19.89','2 (2)','3');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,7,'Hayden TOBIAS','Ohio State','SO','19.86','1 (6)','2');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,8,'Nikolas CURTISS','Iowa','SR','19.74','2 (3)','1');
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,9,'Josh SOBOTA','Kentucky','JR','19.73','1 (4)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,10,'Josh JOHNSON','California','SR','19.39','1 (7)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,11,'John MEYER','LSU','SO','19.35','1 (8)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,12,'Jalil BREWER','Texas','SR','19.33','1 (9)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,13,'Christopher LICATA','Princeton','SR','19.31','2 (4)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,14,'Cooper CAMPBELL','Oklahoma','SR','19.22','2 (5)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,15,'Burger LAMBRECHTS JR.','Nebraska','SR','19.10','2 (6)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,16,'Diego TREVINO','Oklahoma','SO','18.97','2 (7)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,17,'Daniel VIVEROS','Ole Miss','JR','18.82','2 (8)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,18,'Maxwell OTTERDAHL','Nebraska','SO','18.81','1 (10)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,19,'Michael SHOAF','Notre Dame','SO','18.75','2 (9)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,20,'John STEFAN','Notre Dame','SR','18.54','2 (10)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,21,'Bryce FOSTER','Texas A&M','FR','18.52','1 (11)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,22,'Dylan TARGGART','South Carolina','FR','18.12','2 (11)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,23,'Djimon GUMBS','Northwestern St.','SO','16.99','2 (12)',null);
insert into m_SP_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('SP',2022,null,'Santiago BASSO','Alabama','JR','X','1',null);

insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,1,'Tejaswin SHANKAR','Kansas State','SR','2.27','1 (1)','10');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,2,'Darius CARBIN','Georgia','SR','2.24','1 (2)','8');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,3,'Dontavious HILL','Auburn','JR','2.21','1 (3)','6');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,4,'Vernon TURNER','Oklahoma','SR','2.21','1 (4)','5');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,5,'Mitch JACOBSON','Washington St.','SR','2.21','1 (5)','4');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,6,'Bryson DEBERRY','UT-Arlington','SR','2.18','1 (6)','3');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,7,'Trey ALLEN','Louisville','SO','2.18','1 (7)','2');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,8,'Roberto VILCHES','Missouri','JR','2.15','1 (8)','1');
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,9,'Shaun MILLER JR.','Ohio State','SO','2.15','1 (9)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,10,'Earnie SEARS III','USC','SR','2.15','1 (10)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,10,'Corvell TODD','Southern Miss.','JR','2.15','1 (10)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,12,'Caleb WILBORN','Texas Tech','SO','2.15','1 (12)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,13,'Romaine BECKFORD','South Florida','JR','2.15','1 (13)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,14,'Omamuyowi ERHIRE','Mid. Tenn. State','JR','2.15','1 (14)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,15,'Mayson CONNER','Nebraska','JR','2.10','1 (15)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,15,'Kyle ALCINE','Kansas State','SR','2.10','1 (15)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,15,'Kennedy SAUDER','Liberty','FR','2.10','1 (15)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,15,'Jackson MARSEILLE','South Carolina','SO','2.10','1 (15)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,19,'Jeff HOLLIS','Princeton','SR','2.10','1 (19)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,19,'Tony JONES','Wake Forest','JR','2.10','1 (19)',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,null,'Jeremy Cody','Arizona State','SO','NH','1',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,null,'Isaiah HOLMES','Miami (Fla.)','SR','NH','1',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,null,'Carter Bajoit','Texas A&M','SO','NH','1',null);
insert into m_HJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('HJ',2022,null,'Kason O''Riley','Oklahoma','FR','NH','1',null);

insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,1,'Claudio ROMERO','Virginia','FR','66.17','2 (1)','10');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,2,'Mykolas ALEKNA','California','FR','66.15','2 (2)','8');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,3,'Ralford MULLINGS','Arizona State','FR','62.46','2 (4)','6');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,4,'Iffy JOYNER','California','JR','60.75','2 (3)','5');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,5,'Kaleb SIEKMEIER','Minnesota','JR','59.99','1 (1)','4');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,6,'Jeffrey WILLIAMS','Miami (Fla.)','JR','59.86','1 (2)','3');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,7,'Elijah MASON','Washington','SR','59.60','2 (5)','2');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,8,'Jordan JOHNSON','Iowa','SO','59.52','2 (6)','1');
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,9,'Roje STONA','Clemson','JR','58.85','2 (7)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,10,'Turner WASHINGTON','Arizona State','JR','58.33','1 (3)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,11,'Kevin NEDRICK','Liberty','JR','58.28','1 (4)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,12,'Tanner WATSON','Ohio State','SO','57.53','1 (5)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,13,'Samuel WELSH','Harvard','SO','57.27','2 (8)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,14,'Tom YEZEK','Northern Iowa','SR','56.82','1 (6)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,15,'Jacob LEMMON','Virginia','FR','56.77','2 (9)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,16,'Zorawar OTAL','Princeton','SR','55.92','2 (10)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,17,'Sean STAVINOHA','Texas','SO','55.73','1 (7)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,18,'Jamir GIBSON','Army West Point','SR','55.14','1 (8)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,19,'Adar SHEERE','Louisville','JR','55.11','2 (11)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,20,'Kevin SAKSON','Iowa State','SO','54.68','2 (12)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,21,'Jackson MORRIS','Colorado St.','SO','53.12','1 (9)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,22,'Djimon GUMBS','Northwestern St.','SO','53.00','1 (10)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,23,'Nathan REID','Wyoming','SO','49.80','1 (11)',null);
insert into m_DT_final_2022 (Event,Season,Place,Name,Team,Year,Mark,"Flight(pl)",Score) values ('DT',2022,null,'Matthew APPEL','Yale','FR','X','1',null);

insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,1,'Chengetayi MAPAYA','TCU','SR','17.26','0.5','1 (1)','10');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,2,'Emmanuel IHEMEJE','Oregon','SO','17.03','0.3','1 (2)','8');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,3,'Apalos EDWARDS','LSU','FR','16.39','1.2','1 (3)','6');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,4,'Keyshawn KING','Stanford','JR','16.32','-0.7','1 (4)','5');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,5,'Georgi NACHEV','Missouri','JR','16.18','0.8','1 (7)','4');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,6,'Chris WELCH','Texas Tech','JR','16.17','0.3','1 (5)','3');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,7,'Jeremiah DAVIS','Florida State','SO','16.13','0.1','1 (6)','2');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,8,'Nathan CRAWFORD-WALLIS','Prairie View','SO','16.10','0.6','2 (1)','1');
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,9,'Jalen TATE','Tennessee','SR','16.05','-0.2','2 (2)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,10,'Jemuel MILLER','UTSA','FR','16.01','0.1','2 (3)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,11,'RnullLazon BRUMFIELD','Tennessee St.','SR','15.97','0.3','1 (8)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,12,'Salif MANE','Fairleigh Dickinson','JR','15.96','1.0','2 (4)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,13,'Jason SMITH','Long Beach St.','SR','15.91','0.3','2 (5)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,14,'Sean DIXON-BODIE','LSU','SO','15.90','0.4','1 (9)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,15,'Safin WILLS','Purdue','SR','15.86','0.1','2 (6)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,16,'Russell ROBINSON','Miami (Fla.)','SO','15.84','-0.2','1 (10)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,17,'Chauncey CHAMBERS','Virginia Tech','JR','15.82','-0.2','2 (7)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,18,'Jalen SEALS','Texas Tech','SR','15.81','0.8','2 (8)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,19,'Owayne OWENS','Virginia','SO','15.80','0.3','1 (11)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,20,'Daniel FALODE','Harvard','FR','15.77','0.5','2 (9)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,21,'Stacy BROWN JR','Texas','SO','15.70','0.1','2 (10)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,22,'James CARTER','Iowa','JR','15.49','0.5','1 (12)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,23,'Jaren HOLMES','TCU','JR','15.48','-0.1','2 (11)',null);
insert into m_TJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('TJ',2022,24,'Jacore IRVING','Florida State','JR','15.43','-0.2','2 (12)',null);

insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,1,'Wayne PINNOCK','Tennessee','FR','8.00','-0.5','1 (1)','10');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,2,'Jeremiah DAVIS','Florida State','SO','8.00','1.2','1 (5)','8');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,3,'Isaac GRIMES','Florida State','SR','7.97','-0.3','2 (2)','6');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,4,'Carey MCLEOD','Tennessee','SR','7.90','0.1','2 (1)','5');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,5,'Brandon HICKLIN','N. Carolina A&T','SR','7.86','0.5','1 (3)','4');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,6,'AnullNan BRIDGETT','Rutgers','JR','7.85','0.6','1 (2)','3');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,7,'Stacy BROWN JR','Texas','SO','7.81','0.6','1 (4)','2');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,8,'Anthony RILEY','Tennessee','SO','7.80','1.1','2 (3)','1');
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,9,'Cameron CRUMP','Miss State','SR','7.65','0.5','1 (6)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,10,'James CARTER','Iowa','JR','7.60','1.7','1 (7)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,11,'Jeremiah WILLIS','Louisville','SO','7.54','0.2','1 (8)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,12,'Kenson TATE','Lamar','FR','7.53','-0.1','1 (9)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,13,'Jason SMITH','Long Beach St.','SR','7.52','0.1','2 (4)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,14,'Treyshon MALONE','Idaho State','SR','7.50','0.2','1 (10)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,15,'Isaiah HOLMES','Miami (Fla.)','SR','7.48','-0.2','2 (5)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,16,'Kareem MERSAL','Wyoming','SO','7.48','0.1','1 (11)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,17,'Johnny BRACKINS','Baylor','FR','7.47','0.2','2 (6)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,18,'Reinaldo RODRIGUES','Arizona','FR','7.43','-0.1','2 (7)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,19,'Gabriel BINION','Grand Canyon','SO','7.38','-0.3','2 (8)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,20,'Safin WILLS','Purdue','SR','7.35','-0.1','2 (9)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,21,'Aaron JOHNSON','Utah Valley','JR','7.32','0.2','1 (12)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,22,'Christiaan LE ROUX','UTSA','SO','7.31','-0.3','2 (10)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,23,'Russell ROBINSON','Miami (Fla.)','SO','7.06','0.3','2 (11)',null);
insert into m_LJ_final_2022 (Event,Season,Place,Name,Team,Year,Mark,Wind,"Flight(pl)",Score) values ('LJ',2022,24,'Ryan BROWN','Arkansas','JR','6.80','-0.1','2 (12)',null);
