/* List of Teams */
CREATE VIEW TEAMS  as
SELECT team FROM  M_100M_FINAL_2015 UNION
SELECT team FROM  M_100M_FINAL_2016 UNION
SELECT team FROM  M_100M_FINAL_2017 UNION
SELECT team FROM  M_100M_FINAL_2018 UNION
SELECT team FROM  M_100M_FINAL_2019 UNION
SELECT team FROM  M_100M_FINAL_2021 UNION
SELECT team FROM  M_100M_FINAL_2022 UNION
SELECT team FROM  M_100M_SEMIS_2015 UNION
SELECT team FROM  M_100M_SEMIS_2016 UNION
SELECT team FROM  M_100M_SEMIS_2017 UNION
SELECT team FROM  M_100M_SEMIS_2018 UNION
SELECT team FROM  M_100M_SEMIS_2019 UNION
SELECT team FROM  M_100M_SEMIS_2021 UNION
SELECT team FROM  M_100M_SEMIS_2022 UNION
SELECT team FROM  M_10K_FINAL_2015 UNION
SELECT team FROM  M_10K_FINAL_2016 UNION
SELECT team FROM  M_10K_FINAL_2017 UNION
SELECT team FROM  M_10K_FINAL_2018 UNION
SELECT team FROM  M_10K_FINAL_2019 UNION
SELECT team FROM  M_10K_FINAL_2021 UNION
SELECT team FROM  M_10K_FINAL_2022 UNION
SELECT team FROM  M_110H_FINAL_2015 UNION
SELECT team FROM  M_110H_FINAL_2016 UNION
SELECT team FROM  M_110H_FINAL_2017 UNION
SELECT team FROM  M_110H_FINAL_2018 UNION
SELECT team FROM  M_110H_FINAL_2019 UNION
SELECT team FROM  M_110H_FINAL_2021 UNION
SELECT team FROM  M_110H_FINAL_2022 UNION
SELECT team FROM  M_110H_SEMIS_2015 UNION
SELECT team FROM  M_110H_SEMIS_2016 UNION
SELECT team FROM  M_110H_SEMIS_2017 UNION
SELECT team FROM  M_110H_SEMIS_2018 UNION
SELECT team FROM  M_110H_SEMIS_2019 UNION
SELECT team FROM  M_110H_SEMIS_2021 UNION
SELECT team FROM  M_110H_SEMIS_2022 UNION
SELECT team FROM  M_1500M_FINAL_2015 UNION
SELECT team FROM  M_1500M_FINAL_2016 UNION
SELECT team FROM  M_1500M_FINAL_2017 UNION
SELECT team FROM  M_1500M_FINAL_2018 UNION
SELECT team FROM  M_1500M_FINAL_2019 UNION
SELECT team FROM  M_1500M_FINAL_2021 UNION
SELECT team FROM  M_1500M_FINAL_2022 UNION
SELECT team FROM  M_1500M_SEMIS_2015 UNION
SELECT team FROM  M_1500M_SEMIS_2016 UNION
SELECT team FROM  M_1500M_SEMIS_2017 UNION
SELECT team FROM  M_1500M_SEMIS_2018 UNION
SELECT team FROM  M_1500M_SEMIS_2019 UNION
SELECT team FROM  M_1500M_SEMIS_2021 UNION
SELECT team FROM  M_1500M_SEMIS_2022 UNION
SELECT team FROM  M_200M_FINAL_2015 UNION
SELECT team FROM  M_200M_FINAL_2016 UNION
SELECT team FROM  M_200M_FINAL_2017 UNION
SELECT team FROM  M_200M_FINAL_2018 UNION
SELECT team FROM  M_200M_FINAL_2019 UNION
SELECT team FROM  M_200M_FINAL_2021 UNION
SELECT team FROM  M_200M_FINAL_2022 UNION
SELECT team FROM  M_200M_SEMIS_2015 UNION
SELECT team FROM  M_200M_SEMIS_2016 UNION
SELECT team FROM  M_200M_SEMIS_2017 UNION
SELECT team FROM  M_200M_SEMIS_2018 UNION
SELECT team FROM  M_200M_SEMIS_2019 UNION
SELECT team FROM  M_200M_SEMIS_2021 UNION
SELECT team FROM  M_200M_SEMIS_2022 UNION
SELECT team FROM  M_3000M_SC_FINAL_2015 UNION
SELECT team FROM  M_3000M_SC_FINAL_2016 UNION
SELECT team FROM  M_3000M_SC_FINAL_2017 UNION
SELECT team FROM  M_3000M_SC_FINAL_2018 UNION
SELECT team FROM  M_3000M_SC_FINAL_2019 UNION
SELECT team FROM  M_3000M_SC_FINAL_2021 UNION
SELECT team FROM  M_3000M_SC_FINAL_2022 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2015 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2016 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2017 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2018 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2019 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2021 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2022 UNION
SELECT team FROM  M_400H_FINAL_2015 UNION
SELECT team FROM  M_400H_FINAL_2016 UNION
SELECT team FROM  M_400H_FINAL_2017 UNION
SELECT team FROM  M_400H_FINAL_2018 UNION
SELECT team FROM  M_400H_FINAL_2019 UNION
SELECT team FROM  M_400H_FINAL_2021 UNION
SELECT team FROM  M_400H_FINAL_2022 UNION
SELECT team FROM  M_400H_SEMIS_2015 UNION
SELECT team FROM  M_400H_SEMIS_2016 UNION
SELECT team FROM  M_400H_SEMIS_2017 UNION
SELECT team FROM  M_400H_SEMIS_2018 UNION
SELECT team FROM  M_400H_SEMIS_2019 UNION
SELECT team FROM  M_400H_SEMIS_2021 UNION
SELECT team FROM  M_400H_SEMIS_2022 UNION
SELECT team FROM  M_400M_FINAL_2015 UNION
SELECT team FROM  M_400M_FINAL_2016 UNION
SELECT team FROM  M_400M_FINAL_2017 UNION
SELECT team FROM  M_400M_FINAL_2018 UNION
SELECT team FROM  M_400M_FINAL_2019 UNION
SELECT team FROM  M_400M_FINAL_2021 UNION
SELECT team FROM  M_400M_FINAL_2022 UNION
SELECT team FROM  M_400M_SEMIS_2015 UNION
SELECT team FROM  M_400M_SEMIS_2016 UNION
SELECT team FROM  M_400M_SEMIS_2017 UNION
SELECT team FROM  M_400M_SEMIS_2018 UNION
SELECT team FROM  M_400M_SEMIS_2019 UNION
SELECT team FROM  M_400M_SEMIS_2021 UNION
SELECT team FROM  M_400M_SEMIS_2022 UNION
SELECT team FROM  M_4x1_FINAL_2015 UNION
SELECT team FROM  M_4x1_FINAL_2016 UNION
SELECT team FROM  M_4x1_FINAL_2017 UNION
SELECT team FROM  M_4x1_FINAL_2018 UNION
SELECT team FROM  M_4x1_FINAL_2019 UNION
SELECT team FROM  M_4x1_FINAL_2021 UNION
SELECT team FROM  M_4x1_FINAL_2022 UNION
SELECT team FROM  M_4x1_SEMIS_2015 UNION
SELECT team FROM  M_4x1_SEMIS_2016 UNION
SELECT team FROM  M_4x1_SEMIS_2017 UNION
SELECT team FROM  M_4x1_SEMIS_2018 UNION
SELECT team FROM  M_4x1_SEMIS_2019 UNION
SELECT team FROM  M_4x1_SEMIS_2021 UNION
SELECT team FROM  M_4x1_SEMIS_2022 UNION
SELECT team FROM  M_4x4_FINAL_2015 UNION
SELECT team FROM  M_4x4_FINAL_2016 UNION
SELECT team FROM  M_4x4_FINAL_2017 UNION
SELECT team FROM  M_4x4_FINAL_2018 UNION
SELECT team FROM  M_4x4_FINAL_2019 UNION
SELECT team FROM  M_4x4_FINAL_2021 UNION
SELECT team FROM  M_4x4_FINAL_2022 UNION
SELECT team FROM  M_4x4_SEMIS_2015 UNION
SELECT team FROM  M_4x4_SEMIS_2016 UNION
SELECT team FROM  M_4x4_SEMIS_2017 UNION
SELECT team FROM  M_4x4_SEMIS_2018 UNION
SELECT team FROM  M_4x4_SEMIS_2019 UNION
SELECT team FROM  M_4x4_SEMIS_2021 UNION
SELECT team FROM  M_4x4_SEMIS_2022 UNION
SELECT team FROM  M_5K_FINAL_2015 UNION
SELECT team FROM  M_5K_FINAL_2016 UNION
SELECT team FROM  M_5K_FINAL_2017 UNION
SELECT team FROM  M_5K_FINAL_2018 UNION
SELECT team FROM  M_5K_FINAL_2019 UNION
SELECT team FROM  M_5K_FINAL_2021 UNION
SELECT team FROM  M_5K_FINAL_2022 UNION
SELECT team FROM  M_800M_FINAL_2015 UNION
SELECT team FROM  M_800M_FINAL_2016 UNION
SELECT team FROM  M_800M_FINAL_2017 UNION
SELECT team FROM  M_800M_FINAL_2018 UNION
SELECT team FROM  M_800M_FINAL_2019 UNION
SELECT team FROM  M_800M_FINAL_2021 UNION
SELECT team FROM  M_800M_FINAL_2022 UNION
SELECT team FROM  M_800M_SEMIS_2015 UNION
SELECT team FROM  M_800M_SEMIS_2016 UNION
SELECT team FROM  M_800M_SEMIS_2017 UNION
SELECT team FROM  M_800M_SEMIS_2018 UNION
SELECT team FROM  M_800M_SEMIS_2019 UNION
SELECT team FROM  M_800M_SEMIS_2021 UNION
SELECT team FROM  M_800M_SEMIS_2022;



/* Championship by Year Views */
CREATE VIEW NCAA_2015_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2015 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2015 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2015;


CREATE VIEW  NCAA_2016_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2016 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2016 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2016;


CREATE VIEW  NCAA_2017_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2017 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2017 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2017;


CREATE VIEW NCAA_2018_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2018 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2018 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2018;


CREATE VIEW NCAA_2019_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2019 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2019 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2019;


CREATE VIEW NCAA_2021_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2021 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2021 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2021;


CREATE VIEW NCAA_2022_Champs AS
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND,  SCORE FROM m_100m_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_200m_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_800m_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2022 UNION ALL 
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000m_SC_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_3000m_SC_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", WIND, SCORE FROM m_110H_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_400H_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_5K_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_10K_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2022 UNION ALL
SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "HEAT(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2022;


select * from (
	SELECT *, MIN(place) OVER(PARTITION BY TEAM) AS LOWEST_place
	FROM M4x4_VW
	) as best_finish
where lowest_place = place
and upper(round) = 'FINAL'


select * from (
	SELECT *, MIN(TIME) OVER(PARTITION BY TEAM) AS LOWEST_TIME
	FROM M4x4_VW
	) as TEAM_FASTEST
where lowest_time = time;

select * from (
	SELECT *, row_number() OVER(PARTITION BY TEAM) AS rnum
	FROM M4x4_VW
	) as TEAM_FASTEST
where rnum = 1
	ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time