CREATE TABLE MENS_100M_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_100M_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_100M_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_200M_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_200M_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400M_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400M_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_800M_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_800M_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_1500M_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_1500M_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_3000M_SC_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_3000M_SC_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_110H_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	,WIND NUMERIC(10, 2)
	);

CREATE TABLE MENS_110H_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,WIND NUMERIC(10, 2)
	,SCORE INT
	);

CREATE TABLE MENS_400H_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_400H_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_5K_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_10K_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,SCORE INT
	);

CREATE TABLE MENS_4x1_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x1_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);

CREATE TABLE MENS_4x4_SEMIS_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,QUALIFIER VARCHAR(10)
	,"HEAT(pl)" VARCHAR(10)
	);

CREATE TABLE MENS_4x4_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE INT
	,NAME VARCHAR(50) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,TIME VARCHAR(20) NOT NULL
	,TIME_DETAIL VARCHAR(20)
	,REACTION_TIME NUMERIC(5, 3)
	,SCORE INT
	);
