CREATE TABLE M_HT_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2015 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_HT_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2016 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);	

CREATE TABLE M_HT_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2017 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_HT_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2018 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	CREATE TABLE M_HT_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2019 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	CREATE TABLE M_HT_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2022 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_HT_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_PV_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_JT_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
CREATE TABLE M_LJ_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_SP_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_HJ_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);

CREATE TABLE M_DT_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	--,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);
	
	
CREATE TABLE M_TJ_FINAL_2021 (
	Place VARCHAR(10)
	,Name VARCHAR(50) NOT NULL
	,Team VARCHAR(50) NOT NULL
	,Year VARCHAR(2) NOT NULL
	,Mark VARCHAR(50)
	,WIND NUMERIC(10, 2)
	,"Flight(pl)" VARCHAR(50)
	,Score Numeric
	);