CREATE TABLE W_100M_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100M_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100M_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_200M_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_200M_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400M_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400M_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_800M_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_800M_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_1500M_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_1500M_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_3000mSC_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_3000mSC_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_100H_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

CREATE TABLE W_100H_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_400H_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_400H_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_5K_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_10K_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x1_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x1_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_4x4_SEMIS_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

CREATE TABLE W_4x4_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);


CREATE TABLE W_HT_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HT_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_PV_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_JT_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_LJ_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_SP_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HJ_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_DT_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_TJ_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

CREATE TABLE W_HEPT_FINAL_2015 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2016 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2017 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2018 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2019 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2021 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2022 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

CREATE TABLE W_HEPT_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,POINTS VARCHAR(10)
,SCORE NUMERIC(10, 2)
);

create table w_100M_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

create table w_100M_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_200M_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

create table w_200M_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_400M_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_400M_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

create table w_800M_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_800M_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

create table w_1500M_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_1500M_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

create table w_3000mSC_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_3000mSC_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

create table w_100H_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
,WIND VARCHAR(50)
);

create table w_100H_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,WIND VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_400H_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_400H_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

create table w_5K_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

create table w_10K_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,YEAR VARCHAR(2) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,SCORE NUMERIC(10,2)
);

create table w_4x1_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_4x1_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);

create table w_4x4_SEMIS_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,QUALIFIER VARCHAR(10)
,Heat_Pl VARCHAR(10)
);

create table w_4x4_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(20)
,PLACE Varchar(10)
,NAME VARCHAR(50) NOT NULL
,TEAM VARCHAR(50) NOT NULL
,TIME VARCHAR(20) NOT NULL
,TIME_DETAIL VARCHAR(20)
,REACTION_TIME VARCHAR(10)
,SCORE NUMERIC(10,2)
);


create table w_HT_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_PV_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_JT_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_LJ_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_SP_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_HJ_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_DT_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);

create table w_TJ_FINAL_2023 (
GENDER VARCHAR(10)
,EVENT VARCHAR(10)
,SEASON INT
,ROUND VARCHAR(10)
,PLACE VARCHAR(10)
,Name VARCHAR(50)
,Team VARCHAR(50)
,Year VARCHAR(10)
,Mark VARCHAR(50)
,Wind VARCHAR(50)
,Flight_Pl VARCHAR(50)
,SCORE NUMERIC(10,2)
);