CREATE TABLE W_HEPT_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE W_HEPT_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2015 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2016 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2017 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2018 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2019 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2021 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);

CREATE TABLE M_DEC_FINAL_2022 (
	EVENT VARCHAR(50)
	,SEASON INT
	,ROUND VARCHAR(20)
	,PLACE Varchar(10)
	,NAME VARCHAR(50) NOT NULL
	,YEAR VARCHAR(2) NOT NULL
	,TEAM VARCHAR(50) NOT NULL
	,POINTS VARCHAR(10)
	,SCORE NUMERIC(10, 2)
	);


insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','1','Akela Jones','JR','Kansas State','6371','10');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','2','Kendell Williams','SO','Georgia','6223','8');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','3','Quintunya Chapman','SR','Georgia','6147','6');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','4','Erica Bougard','JR','Miss State','6050','5');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','5','Jess Herauf','JR','Minnesota','5965','4');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','6','Jena Hemann','SR','Texas A&M','5913','3');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','7','Xenia Rahn','SR','North Carolina','5851','2');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','8','Nikki Larch-Miller','JR','Wichita State','5806','1');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','9','Alex Gochenour','JR','Arkansas','5806','0.5');
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','10','Georgia Ellenwood','SO','Wisconsin','5786',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','11','Sarah Chauchard','SR','Eastern Michigan','5782',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','12','Deanna Latham','SR','Wisconsin','5778',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','13','Fabia McDonald','SR','Mississippi','5757',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','14','Chari Hawkins','SR','Utah State','5750',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','15','Grete Sadeiko','SO','Florida State','5730',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','16','Taliyah Brooks','FR','Arkansas','5717',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','17','Tatum Souza','SR','UCLA','5604',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','18','Alissa Brooks-Johnson','SO','Washington St.','5572',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','19','Ashlee Moore','FR','Oregon','5486',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','20','Abrianna Torres','JR','Colorado','5483',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','21','Brittany Kelly','FR','Mississippi','5394',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL','22','Jallycia Pearson','SR','UTEP','5320',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL',null,'Lindsey Vollmer','SR','Kansas','DNF',null);
insert into W_HEPT_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2015','FINAL',null,'Teddi Maslowski','JR','Duke','DNF',null);

insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','1','Kendell Williams','JR','Georgia','6225','10');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','2','Erica Bougard','SR','Miss State','6088','8');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','3','Akela Jones','SR','Kansas State','6063','6');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','4','Alex Gochenour','SR','Arkansas','5962','5');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','5','Georgia Ellenwood','JR','Wisconsin','5935','4');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','6','Payton Stumbaugh','SO','Arkansas','5868','3');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','7','Jess Lehman','SR','Minnesota','5835','2');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','8','Paige Knodle','SR','Northern Iowa','5833','1');
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','9','Annie Kunz','SR','Texas A&M','5784',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','10','Leigha Brown','JR','Arkansas','5677',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','11','Grete Sadeiko','JR','Florida State','5658',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','12','Jaclyn Siefring','SO','Akron','5626',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','13','Lucia Mokrasova','SO','UTEP','5569',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','14','Alyssa Thompson','JR','Arizona','5514',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','15','Lucija Cvitanovic','SR','SMU','5482',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','16','Liz Harper','JR','Washington St.','5446',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','17','Ashtin Zamzow','SO','Texas','5443',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','18','Teddi Maslowski','SR','Duke','5382',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','19','Carly Loeffel','SR','Notre Dame','5373',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','20','Riley Cooks','JR','Long Beach St.','5372',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','21','Elizabeth Dadzie','JR','Mid. Tenn. State','5298',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','22','Jessica Green','SR','Colorado St.','5032',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL','23','Clairwin Dameus','SR','Tennessee St.','5030',null);
insert into W_HEPT_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2016','FINAL',null,'Taliyah Brooks','SO','Arkansas','DNF',null);

insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','1','Kendell Williams','SR','Georgia','6265','10');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','2','Nina Schultz','FR','Kansas State','5959','8');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','3','Taliyah Brooks','JR','Arkansas','5795','6');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','4','Leigha Brown','SR','Arkansas','5694','5');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','5','Jaclyn Siefring','JR','Akron','5663','4');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','6','Alissa Brooks-Johnson','JR','Washington St.','5658','3');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','7','Jordan Gray','SO','Kennesaw State','5621','2');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','8','Kaylee Hinton','SO','Texas Tech','5580','1');
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','9','Nicole Wadden','SR','Nevada','5575',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','10','Kara Hallock','SR','Oregon State','5444',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','11','Breanne Borman','SR','Wichita State','5405',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','12','Gavyn Yetter','SR','Wichita State','5348',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','13','Jenna Pfeiffer','SR','Baylor','5303',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','14','Elizabeth Dadzie','SR','Mid. Tenn. State','5268',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','15','Riley Cooks','SR','Long Beach St.','5256',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','16','Tori Usgaard','SR','UC Santa Barbara','5245',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','17','Lucia Mokrasova','JR','UTEP','5172',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL','18','Holly Hankenson','SO','Louisville','5133',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Payton Stumbaugh','JR','Arkansas','DNF',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Nikki Larch-Miller','SR','Wichita State','DNF',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Louisa Grauvogel','FR','Georgia','DNF',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Melissa-Maree Farrington','SR','Florida State','DNF',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Madeline Holmberg','SO','Penn State','DNF',null);
insert into W_HEPT_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2017','FINAL',null,'Kelsey Herman','SO','Arkansas','DNF',null);

insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','1','Georgia Ellenwood','SR','Wisconsin','6146','10');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','2','Louisa Grauvogel','SO','Georgia','6074','8');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','3','Madeline Holmberg','JR','Penn State','5833','6');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','4','Kendall Gustafson','SR','UCLA','5800','5');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','5','Amanda Froeynes','FR','Florida','5794','4');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','6','Alissa Brooks-Johnson','SR','Washington St.','5789','3');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','7','Nina Schultz','SO','Kansas State','5778','2');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','8','Tyra Gittens','FR','Texas A&M','5748','1');
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','9','Ayesha Champagnie','JR','Minnesota','5740',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','10','Jaclyn Siefring','SR','Akron','5725',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','11','Ashtin Zamzow','SR','Texas','5667',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','12','Hope Bender','JR','UC Santa Barbara','5653',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','13','Maya Neal','JR','Tennessee','5555',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','14','Shaina Burns','SR','Texas A&M','5553',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','15','Patricia Ortega','SR','Akron','5542',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','16','Lyndsey Lopes','JR','USC','5504',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','17','Aliyah Whisby','FR','Kennesaw State','5490',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','18','Aaron Howell','SR','Michigan','5404',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','19','Emile Berge','SO','South Alabama','5314',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL','20','Ariel Okorie','SO','Kansas State','5189',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL',null,'Michelle Atherley','SO','Miami','DNF',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL',null,'Grace McKenzie','SO','McNeese State','DNF',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL',null,'Kaylee Hinton','JR','Texas Tech','DNF',null);
insert into W_HEPT_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2018','FINAL',null,'Alyssa Thompson','SR','Arizona','DNF',null);

insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','1','Ashtin Zamzow','SR','Texas','6222','10');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','2','Tyra Gittens','SO','Texas A&M','6049','8');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','3','Michelle Atherley','JR','Miami (Fla.)','6014','6');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','4','Hope Bender','SR','UC Santa Barbara','5955','5');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','5','Erinn Beattie','SR','UC Davis','5924','4');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','6','Amanda Froeynes','SO','Florida','5891','3');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','7','Jordan Gray','SR','Kennesaw State','5846','2');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','8','Lauren Taubert','JR','Kansas State','5793','1');
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','9','Hannah Rusnak','SO','Washington','5779',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','10','Erin Marsh','SO','Duke','5707',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','11','Sterling Lester','FR','Georgia','5694',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','12','Jestena Mattson','SR','Fresno State','5576',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','13','Nicola Ader','SO','Nevada','5571',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','14','Carly Paul','SR','Brown','5535',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','15','Emilie Berge','JR','South Alabama','5493',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','16','Asya Reynolds','JR','Michigan State','5487',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','17','Tria Simmons','SR','Iowa','5479',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','18','Ariel Okorie','JR','Kansas State','5439',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','19','Beatrice Juskeviciute','FR','Cornell','5438',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','20','Christina Chenault','JR','UCLA','5386',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','21','Amanda Levin','SR','North Dakota State','5332',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','22','Michaela Wenning','SR','Colorado','5274',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','23','Jenny Kimbro','JR','Iowa','5023',null);
insert into W_HEPT_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2019','FINAL','24','Maja Wichhart-Donzo','SR','Colorado','4554',null);

insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','1','Tyra Gittens','JR','Texas A&M','6285','10');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','2','Michelle Atherley','SR','Miami (Fla.)','6067','8');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','3','Kristine Blazevica','FR','Texas','5984','6');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','4','Erin Marsh','JR','Duke','5924','5');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','5','Ida Eikeng','JR','Washington','5920','4');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','6','Madeline Nickal','SR','Penn State','5864','3');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','7','Asya Reynolds','SR','Georgia','5754','2');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','8','Beatrice Juskeviciute','SO','Cornell','5694','1');
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','9','Shayla Broughton','SR','Miss State','5652',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','10','Allie Jones','SO','Stanford','5623',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','11','Jadin O''Brien','FR','Notre Dame','5545',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','12','Lyndsey Lopes','SR','Washington','5542',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','13','Kaitlin Smith','SR','Houston Baptist','5520',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','14','Kaylee Hinton','SR','Texas Tech','5498',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','15','Lauren Taubert','SR','Kansas State','5436',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','16','Ariel Okorie','SR','Kansas State','5420',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','17','Zoe Hughes','JR','Duke','5385',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','18','Jenny Kimbro','SR','Iowa','5381',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','19','Callie Jones','JR','Texas Tech','5270',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','20','Emma Nwofor','SR','Ohio State','5208',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL','21','Skylar Sieben','SO','Arizona','4736',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL',null,'Natosha Jordan','SR','Auburn','DNF',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL',null,'Grace McKenzie','SR','McNeese State','DNF',null);
insert into W_HEPT_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2021','FINAL',null,'Nicola Ader','JR','Nevada','DNF',null);

insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','1','Anna Hall','SO','Florida','6385','10');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','2','Ida Eikeng','JR','Washington','5939','8');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','3','Erin Marsh','SR','Duke','5929','6');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','4','Allie Jones','JR','Stanford','5823','5');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','5','Sterling Lester','JR','Florida','5751','4');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','6','Lexie Keller','JR','Colorado St.','5722','3');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','7','Beatrice Juskeviciute','SR','Cornell','5721','2');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','8','Halley Folsom','SR','BYU','5692','1');
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','9','Nicola Ader','SR','Nevada','5647',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','10','Safiya John','JR','Arkansas-Pine Bluff','5626',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','11','Kaitlin Smith','SR','Houston Baptist','5617',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','12','Avery McMullen','SO','Colorado','5600',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','13','Alexus Pyles','SR','Ohio State','5491',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','14','Callie Jones','SR','Texas Tech','5436',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','15','Bailey Golden','SO','Oklahoma State','5415',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','16','Brittany Floyd','SR','UCF','5410',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','17','Elise Ulseth','SO','North Dakota','5362',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','18','Anna Bush','JR','Wake Forest','5361',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','19','Jade Bontke','SR','UT-Arlington','5300',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','20','Olivija Vaitaityte','FR','Oklahoma State','5287',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','21','Kristine Blazevica','SO','Texas','4756',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL','22','Urte Bacianskaite','SO','Kansas State','4608',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL',null,'Isabel Wakefield','JR','Duke','DNF',null);
insert into W_HEPT_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('HEPT','2022','FINAL',null,'Timara Chapman','JR','NC State','DNF',null);

insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','1','Maicel Uibo','JR','Georgia','8356','10');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','2','Pau Tonnesen','JR','Arizona','8247','8');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','3','Dakotah Keys','SR','Oregon','7863','6');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','4','Harrison Williams','FR','Stanford','7806','5');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','5','Tim Ehrhardt','SO','Michigan State','7677','4');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','6','Stephen Soerens','SR','Princeton','7669','3');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','7','Wolf Mahler','SO','Texas','7650','2');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','8','Scott Filip','SO','Rice','7647','1');
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','9','Atsu Nyamadi','JR','Mid. Tenn. State','7567',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','10','Markus Leemet','SO','South Carolina','7549',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','11','K''vonte Scott','SR','Charlotte','7541',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','12','Steele Wasik','FR','UCLA','7519',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','13','Zach Taylor','SO','Miss State','7376',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','14','Joshua Mulder','JR','Kennesaw State','7244',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','15','Nathanael Franks','SR','Arkansas','7099',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','16','Taylor Sanderson','JR','Iowa State','6808',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','17','Joe Delgado','FR','Oregon','6697',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL','18','Mitch Modin','SO','Oregon','6666',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Mike Morgan','JR','Buffalo','DNF',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Garrett Scantling','SR','Georgia','DNF',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Dino Dodig','SO','Washington St.','DNF',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Solomon Ijah','JR','Eastern Michigan','DNF',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Devon Williams','SO','Georgia','DNF',null);
insert into M_DEC_FINAL_2015 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2015','FINAL',null,'Luca Wieland','SO','Minnesota','DNF',null);

insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','1','Lindon Victor','JR','Texas A&M','8379','10');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','2','Zach Ziemek','SR','Wisconsin','8300','8');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','3','Maicel Uibo','SR','Georgia','8294','6');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','4','Pau Tonnesen','SR','Arizona','8103','5');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','5','Harrison Williams','SO','Stanford','8032','4');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','6','Solomon Simmons','SR','Eastern Michigan','7936','3');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','7','Karl Saluri','SO','Georgia','7934','2');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','8','Steven Bastien','JR','Michigan','7917','1');
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','9','Devon Williams','JR','Georgia','7912',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','10','Atsu Nyamadi','SR','Mid. Tenn. State','7709',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','11','Tim Duckworth','SO','Kentucky','7596',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','12','Cody Walton','SO','Nebraska','7567',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','13','Mitch Modin','JR','Oregon','7556',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','14','Joe Delgado','SO','Oregon','7432',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','15','Taylor Sanderson','SR','Iowa State','7368',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','16','Ser Whitaker','SR','Missouri','7194',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','17','Luis Hanssler','SR','Memphis','7148',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','18','Derek Jacobus','JR','Arkansas','7011',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','19','Jackson Walker','JR','BYU','7004',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','20','Brandon Mortensen','SR','Wisconsin','6971',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL','21','Alex McCune','SR','Akron','6572',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL',null,'Ibn Short','JR','Kentucky','DNF',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL',null,'Brad Culp','JR','Arkansas','DNF',null);
insert into M_DEC_FINAL_2016 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2016','FINAL',null,'William Dougherty','SO','Iowa','DNF',null);

insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','1','Lindon Victor','SR','Texas A&M','8390','10');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','2','Devon Williams','SR','Georgia','8181','8');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','3','Luca Wieland','SR','Minnesota','8146','6');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','4','Steven Bastien','SR','Michigan','8015','5');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','5','Scott Filip','JR','Rice','7867','4');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','6','Hunter Veith','JR','Wichita State','7866','3');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','7','Cody Walton','JR','Nebraska','7813','2');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','8','Wolf Mahler','SR','Texas','7737','1');
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','9','TJ Lawson','FR','Kent State','7725',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','10','Steele Wasik','JR','Texas','7642',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','11','Daniel Golubovic','SR','Duke','7634',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','12','Joe Delgado','JR','Oregon','7590',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','13','Gabe Moore','SO','Arkansas','7527',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','14','Tim Ehrhardt','JR','Michigan State','7455',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','15','Mitch Modin','SR','Oregon','7446',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','16','Josh Cogdill','SR','Colorado St.','7258',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','17','William Dougherty','JR','Iowa','7199',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','18','Derek Jacobus','JR','Arkansas','7126',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','19','Tim Duckworth','JR','Kentucky','7026',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL','20','Jackson Walker','SR','BYU','6821',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL',null,'Hunter Price','JR','Colorado St.','DNF',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL',null,'Markus Leemet','JR','South Carolina','DNF',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL',null,'Kari Saluri','JR','Georgia','DNF',null);
insert into M_DEC_FINAL_2017 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2017','FINAL',null,'Jack Lint','SO','Virginia','DNF',null);

insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','1','Tim Duckworth','SR','Kentucky','8336','10');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','2','Karl Saluri','SR','Georgia','8137','8');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','3','Johannes Erm','FR','Georgia','8046','6');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','4','Joe Delgado','SR','Louisville','7852','5');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','5','Scott Filip','SR','Rice','7803','4');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','6','Tim Ehrhardt','SR','Michigan State','7736','3');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','7','Markus Ballengee','SO','Liberty','7722','2');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','8','Kevin Nielsen','SR','BYU','7695','1');
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','9','Gabe Moore','JR','Arkansas','7670',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','10','Nick Guerrant','SO','Michigan State','7619',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','11','Trent Nytes','JR','Wisconsin','7609',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','12','Adrian Riley','SR','UTSA','7520',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','13','William Dougherty','SR','Iowa','7467',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','14','Aaron Booth','SO','Kansas State','7458',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','15','Benjamin Ose','JR','Dartmouth','7237',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','16','Derek Jacobus','SR','Arkansas','7236',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','17','Sawyer Smith','SR','Wisconsin','6583',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL','18','Nathan Hite','JR','Texas A&M','6518',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'Harrison Williams','JR','Stanford','DNF',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'TJ Lawson','SO','Kent State','DNF',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'Rauno Liiitmae','SR','Missouri','DNF',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'Steele Wasik','JR','Texas','DNF',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'Nathaniel Mechler','SO','Houston','DNF',null);
insert into M_DEC_FINAL_2018 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2018','FINAL',null,'Hunter Veith','SR','Wichita State','DNF',null);

insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','1','Johannes Erm','SO','Georgia','8352','10');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','2','Harrison Williams','SR','Stanford','8010','8');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','3','Gabe Moore','SR','Arkansas','7780','6');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','4','Jack Lint','SR','Michigan','7738','5');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','5','Max Vollmer','FR','Oregon','7703','4');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','6','Aaron Booth','JR','Kansas State','7680','3');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','7','Denim Rogers','SO','Houston Baptist','7596','2');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','8','Trent Nytes','SR','Wisconsin','7516','1');
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','9','Benjamin Ose','SR','Dartmouth','7445',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','10','Isaiah Martin','FR','Purdue','7398',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','11','Brian Matthews','JR','BYU','7394',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','12','Charlie Card-Childers','SR','Rice','7365',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','13','Nathan Hite','SR','Texas A&M','7348',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','14','Ben Johnson','SR','Wichita State','7329',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL','15','Wade Walder','JR','Butler','7090',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Ayden Owens','FR','USC','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Axel Hubert','FR','Texas Tech','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Tyler Nelson','SR','UC Santa Barbara','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Paris Williams','JR','Kennesaw State','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Gary Haasbroek','FR','UTSA','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Hunter Powell','SR','Colorado St.','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Noah Swaby','FR','Penn State','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'TJ Lawson','JR','Kent State','DNF',null);
insert into M_DEC_FINAL_2019 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2019','FINAL',null,'Simone Fassina','JR','Kansas State','DNF',null);

insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','1','Karel Tilga','SO','Georgia','8261','10');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','2','Ayden Owens','SO','Michigan','8114','8');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','3','Markus Ballengee','JR','Arkansas','7861','6');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','4','Leo Neugebauer','FR','Texas','7697','5');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','5','Alex Spyridonidis','JR','Auburn','7665','4');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','6','Aaron Booth','JR','Long Beach St.','7644','3');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','7','Will Daniels','SR','Iowa','7635','2');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','8','Max Vollmer','SO','Oregon','7633','1');
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','9','Wade Walder','SR','Michigan State','7565',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','10','Isaiah Martin','SO','Purdue','7542',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','11','Heath Baldwin','FR','Michigan','7522',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','12','Joseph Keys','JR','Marquette','7479',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','13','Noah Swaby','SO','Penn State','7428',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','14','Teddy Frid','SR','Minnesota','7330',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','15','Denim Rogers','SR','Houston Baptist','7233',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','16','Josh Farmer','SO','UC Irvine','7206',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','17','Dallin Vorkink','SO','BYU','6388',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL','18','Jordan Torney','JR','Connecticut','6230',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Asani Hylton','JR','Stephen F. Austin','DNF',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Daniel Spejcher','SO','Arkansas','DNF',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Damien Berthenet','SR','Cinncinnati','DNF',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Austin West','FR','Iowa','DNF',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Jack Turner','FR','UTSA','DNF',null);
insert into M_DEC_FINAL_2021 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2021','FINAL',null,'Scott Boon','JR','Houston Baptist','DNF',null);

insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','1','Ayden Owens-Delerme','JR','Arkansas','8457','10');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','2','Leo Neugebauer','SO','Texas','8362','8');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','3','Kyle Garland','SO','Georgia','8333','6');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','4','Lucas Van Klaveren','SR','UT-Arlington','8015','5');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','5','Austin West','SO','Iowa','7886','4');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','6','Asani Hylton','SR','Stephen F. Austin','7748','3');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','7','Daniel Spejcher','JR','Arkansas','7744','2');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','8','JJ Ply','SR','Abilene Christian','7739','1');
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','9','Isaiah Martin','SR','Purdue','7708',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','10','Yariel Soto','SO','Tennessee','7668',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','11','Dallin Vorkink','JR','BYU','7592',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','12','Emil Uhlin','FR','Kansas State','7546',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','13','Heath Baldwin','SO','Michigan State','7538',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','14','Josh Farmer','JR','UC Irvine','7519',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','15','Oliver Thorner','SO','Washington','7473',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','16','Kristo Simulask','JR','Oklahoma','7457',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','17','Trpimir Siroki','JR','Texas A&M-CC','7431',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','18','Alexander Jung','FR','Kansas','7341',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','19','Hakim McMorris','JR','California','6958',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL','20','Ryan Talbot','SO','Michigan State','6863',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL',null,'Max Vollmer','JR','Oregon','DNF',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL',null,'Alex Spyridonidis','SR','Auburn','DNF',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL',null,'Johannes Erm','SR','Georgia','DNF',null);
insert into M_DEC_FINAL_2022 (EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,POINTS,SCORE) values ('DEC','2022','FINAL',null,'Felix Wolter','SR','Pittsburgh','DNF',null);