/* List of Teams */
CREATE VIEW TEAMS  as
SELECT team FROM  M_100M_FINAL_2015 UNION
SELECT team FROM  M_100M_FINAL_2016 UNION
SELECT team FROM  M_100M_FINAL_2017 UNION
SELECT team FROM  M_100M_FINAL_2018 UNION
SELECT team FROM  M_100M_FINAL_2019 UNION
SELECT team FROM  M_100M_FINAL_2021 UNION
SELECT team FROM  M_100M_FINAL_2022 UNION
SELECT team FROM  M_100M_SEMIS_2015 UNION
SELECT team FROM  M_100M_SEMIS_2016 UNION
SELECT team FROM  M_100M_SEMIS_2017 UNION
SELECT team FROM  M_100M_SEMIS_2018 UNION
SELECT team FROM  M_100M_SEMIS_2019 UNION
SELECT team FROM  M_100M_SEMIS_2021 UNION
SELECT team FROM  M_100M_SEMIS_2022 UNION
SELECT team FROM  M_10K_FINAL_2015 UNION
SELECT team FROM  M_10K_FINAL_2016 UNION
SELECT team FROM  M_10K_FINAL_2017 UNION
SELECT team FROM  M_10K_FINAL_2018 UNION
SELECT team FROM  M_10K_FINAL_2019 UNION
SELECT team FROM  M_10K_FINAL_2021 UNION
SELECT team FROM  M_10K_FINAL_2022 UNION
SELECT team FROM  M_110H_FINAL_2015 UNION
SELECT team FROM  M_110H_FINAL_2016 UNION
SELECT team FROM  M_110H_FINAL_2017 UNION
SELECT team FROM  M_110H_FINAL_2018 UNION
SELECT team FROM  M_110H_FINAL_2019 UNION
SELECT team FROM  M_110H_FINAL_2021 UNION
SELECT team FROM  M_110H_FINAL_2022 UNION
SELECT team FROM  M_110H_SEMIS_2015 UNION
SELECT team FROM  M_110H_SEMIS_2016 UNION
SELECT team FROM  M_110H_SEMIS_2017 UNION
SELECT team FROM  M_110H_SEMIS_2018 UNION
SELECT team FROM  M_110H_SEMIS_2019 UNION
SELECT team FROM  M_110H_SEMIS_2021 UNION
SELECT team FROM  M_110H_SEMIS_2022 UNION
SELECT team FROM  M_1500M_FINAL_2015 UNION
SELECT team FROM  M_1500M_FINAL_2016 UNION
SELECT team FROM  M_1500M_FINAL_2017 UNION
SELECT team FROM  M_1500M_FINAL_2018 UNION
SELECT team FROM  M_1500M_FINAL_2019 UNION
SELECT team FROM  M_1500M_FINAL_2021 UNION
SELECT team FROM  M_1500M_FINAL_2022 UNION
SELECT team FROM  M_1500M_SEMIS_2015 UNION
SELECT team FROM  M_1500M_SEMIS_2016 UNION
SELECT team FROM  M_1500M_SEMIS_2017 UNION
SELECT team FROM  M_1500M_SEMIS_2018 UNION
SELECT team FROM  M_1500M_SEMIS_2019 UNION
SELECT team FROM  M_1500M_SEMIS_2021 UNION
SELECT team FROM  M_1500M_SEMIS_2022 UNION
SELECT team FROM  M_200M_FINAL_2015 UNION
SELECT team FROM  M_200M_FINAL_2016 UNION
SELECT team FROM  M_200M_FINAL_2017 UNION
SELECT team FROM  M_200M_FINAL_2018 UNION
SELECT team FROM  M_200M_FINAL_2019 UNION
SELECT team FROM  M_200M_FINAL_2021 UNION
SELECT team FROM  M_200M_FINAL_2022 UNION
SELECT team FROM  M_200M_SEMIS_2015 UNION
SELECT team FROM  M_200M_SEMIS_2016 UNION
SELECT team FROM  M_200M_SEMIS_2017 UNION
SELECT team FROM  M_200M_SEMIS_2018 UNION
SELECT team FROM  M_200M_SEMIS_2019 UNION
SELECT team FROM  M_200M_SEMIS_2021 UNION
SELECT team FROM  M_200M_SEMIS_2022 UNION
SELECT team FROM  M_3000mSC_FINAL_2015 UNION
SELECT team FROM  M_3000mSC_FINAL_2016 UNION
SELECT team FROM  M_3000mSC_FINAL_2017 UNION
SELECT team FROM  M_3000mSC_FINAL_2018 UNION
SELECT team FROM  M_3000mSC_FINAL_2019 UNION
SELECT team FROM  M_3000mSC_FINAL_2021 UNION
SELECT team FROM  M_3000mSC_FINAL_2022 UNION
SELECT team FROM  M_3000mSC_SEMIS_2015 UNION
SELECT team FROM  M_3000mSC_SEMIS_2016 UNION
SELECT team FROM  M_3000mSC_SEMIS_2017 UNION
SELECT team FROM  M_3000mSC_SEMIS_2018 UNION
SELECT team FROM  M_3000mSC_SEMIS_2019 UNION
SELECT team FROM  M_3000mSC_SEMIS_2021 UNION
SELECT team FROM  M_3000mSC_SEMIS_2022 UNION
SELECT team FROM  M_400H_FINAL_2015 UNION
SELECT team FROM  M_400H_FINAL_2016 UNION
SELECT team FROM  M_400H_FINAL_2017 UNION
SELECT team FROM  M_400H_FINAL_2018 UNION
SELECT team FROM  M_400H_FINAL_2019 UNION
SELECT team FROM  M_400H_FINAL_2021 UNION
SELECT team FROM  M_400H_FINAL_2022 UNION
SELECT team FROM  M_400H_SEMIS_2015 UNION
SELECT team FROM  M_400H_SEMIS_2016 UNION
SELECT team FROM  M_400H_SEMIS_2017 UNION
SELECT team FROM  M_400H_SEMIS_2018 UNION
SELECT team FROM  M_400H_SEMIS_2019 UNION
SELECT team FROM  M_400H_SEMIS_2021 UNION
SELECT team FROM  M_400H_SEMIS_2022 UNION
SELECT team FROM  M_400M_FINAL_2015 UNION
SELECT team FROM  M_400M_FINAL_2016 UNION
SELECT team FROM  M_400M_FINAL_2017 UNION
SELECT team FROM  M_400M_FINAL_2018 UNION
SELECT team FROM  M_400M_FINAL_2019 UNION
SELECT team FROM  M_400M_FINAL_2021 UNION
SELECT team FROM  M_400M_FINAL_2022 UNION
SELECT team FROM  M_400M_SEMIS_2015 UNION
SELECT team FROM  M_400M_SEMIS_2016 UNION
SELECT team FROM  M_400M_SEMIS_2017 UNION
SELECT team FROM  M_400M_SEMIS_2018 UNION
SELECT team FROM  M_400M_SEMIS_2019 UNION
SELECT team FROM  M_400M_SEMIS_2021 UNION
SELECT team FROM  M_400M_SEMIS_2022 UNION
SELECT team FROM  M_4x1_FINAL_2015 UNION
SELECT team FROM  M_4x1_FINAL_2016 UNION
SELECT team FROM  M_4x1_FINAL_2017 UNION
SELECT team FROM  M_4x1_FINAL_2018 UNION
SELECT team FROM  M_4x1_FINAL_2019 UNION
SELECT team FROM  M_4x1_FINAL_2021 UNION
SELECT team FROM  M_4x1_FINAL_2022 UNION
SELECT team FROM  M_4x1_SEMIS_2015 UNION
SELECT team FROM  M_4x1_SEMIS_2016 UNION
SELECT team FROM  M_4x1_SEMIS_2017 UNION
SELECT team FROM  M_4x1_SEMIS_2018 UNION
SELECT team FROM  M_4x1_SEMIS_2019 UNION
SELECT team FROM  M_4x1_SEMIS_2021 UNION
SELECT team FROM  M_4x1_SEMIS_2022 UNION
SELECT team FROM  M_4x4_FINAL_2015 UNION
SELECT team FROM  M_4x4_FINAL_2016 UNION
SELECT team FROM  M_4x4_FINAL_2017 UNION
SELECT team FROM  M_4x4_FINAL_2018 UNION
SELECT team FROM  M_4x4_FINAL_2019 UNION
SELECT team FROM  M_4x4_FINAL_2021 UNION
SELECT team FROM  M_4x4_FINAL_2022 UNION
SELECT team FROM  M_4x4_SEMIS_2015 UNION
SELECT team FROM  M_4x4_SEMIS_2016 UNION
SELECT team FROM  M_4x4_SEMIS_2017 UNION
SELECT team FROM  M_4x4_SEMIS_2018 UNION
SELECT team FROM  M_4x4_SEMIS_2019 UNION
SELECT team FROM  M_4x4_SEMIS_2021 UNION
SELECT team FROM  M_4x4_SEMIS_2022 UNION
SELECT team FROM  M_5K_FINAL_2015 UNION
SELECT team FROM  M_5K_FINAL_2016 UNION
SELECT team FROM  M_5K_FINAL_2017 UNION
SELECT team FROM  M_5K_FINAL_2018 UNION
SELECT team FROM  M_5K_FINAL_2019 UNION
SELECT team FROM  M_5K_FINAL_2021 UNION
SELECT team FROM  M_5K_FINAL_2022 UNION
SELECT team FROM  M_800M_FINAL_2015 UNION
SELECT team FROM  M_800M_FINAL_2016 UNION
SELECT team FROM  M_800M_FINAL_2017 UNION
SELECT team FROM  M_800M_FINAL_2018 UNION
SELECT team FROM  M_800M_FINAL_2019 UNION
SELECT team FROM  M_800M_FINAL_2021 UNION
SELECT team FROM  M_800M_FINAL_2022 UNION
SELECT team FROM  M_800M_SEMIS_2015 UNION
SELECT team FROM  M_800M_SEMIS_2016 UNION
SELECT team FROM  M_800M_SEMIS_2017 UNION
SELECT team FROM  M_800M_SEMIS_2018 UNION
SELECT team FROM  M_800M_SEMIS_2019 UNION
SELECT team FROM  M_800M_SEMIS_2021 UNION
SELECT team FROM  M_800M_SEMIS_2022 UNION
SELECT team FROM m_HT_FINAL_2015 UNION
SELECT team FROM m_PV_FINAL_2015 UNION
SELECT team FROM m_JT_FINAL_2015 UNION
SELECT team FROM m_LJ_FINAL_2015 UNION
SELECT team FROM m_SP_FINAL_2015 UNION
SELECT team FROM m_HJ_FINAL_2015 UNION
SELECT team FROM m_DT_FINAL_2015 UNION
SELECT team FROM m_TJ_FINAL_2015 UNION
SELECT team FROM m_HT_FINAL_2016 UNION
SELECT team FROM m_PV_FINAL_2016 UNION
SELECT team FROM m_JT_FINAL_2016 UNION
SELECT team FROM m_LJ_FINAL_2016 UNION
SELECT team FROM m_SP_FINAL_2016 UNION
SELECT team FROM m_HJ_FINAL_2016 UNION
SELECT team FROM m_DT_FINAL_2016 UNION
SELECT team FROM m_TJ_FINAL_2016 UNION
SELECT team FROM m_HT_FINAL_2017 UNION
SELECT team FROM m_PV_FINAL_2017 UNION
SELECT team FROM m_JT_FINAL_2017 UNION
SELECT team FROM m_LJ_FINAL_2017 UNION
SELECT team FROM m_SP_FINAL_2017 UNION
SELECT team FROM m_HJ_FINAL_2017 UNION
SELECT team FROM m_DT_FINAL_2017 UNION
SELECT team FROM m_TJ_FINAL_2017 UNION
SELECT team FROM m_HT_FINAL_2018 UNION
SELECT team FROM m_PV_FINAL_2018 UNION
SELECT team FROM m_JT_FINAL_2018 UNION
SELECT team FROM m_LJ_FINAL_2018 UNION
SELECT team FROM m_SP_FINAL_2018 UNION
SELECT team FROM m_HJ_FINAL_2018 UNION
SELECT team FROM m_DT_FINAL_2018 UNION
SELECT team FROM m_TJ_FINAL_2018 UNION
SELECT team FROM m_HT_FINAL_2019 UNION
SELECT team FROM m_PV_FINAL_2019 UNION
SELECT team FROM m_JT_FINAL_2019 UNION
SELECT team FROM m_LJ_FINAL_2019 UNION
SELECT team FROM m_SP_FINAL_2019 UNION
SELECT team FROM m_HJ_FINAL_2019 UNION
SELECT team FROM m_DT_FINAL_2019 UNION
SELECT team FROM m_HT_FINAL_2021 UNION
SELECT team FROM m_PV_FINAL_2021 UNION
SELECT team FROM m_JT_FINAL_2021 UNION
SELECT team FROM m_LJ_FINAL_2021 UNION
SELECT team FROM m_SP_FINAL_2021 UNION
SELECT team FROM m_HJ_FINAL_2021 UNION
SELECT team FROM m_DT_FINAL_2021 UNION
SELECT team FROM m_TJ_FINAL_2021 UNION
SELECT team FROM m_HT_FINAL_2022 UNION
SELECT team FROM m_PV_FINAL_2022 UNION
SELECT team FROM m_JT_FINAL_2022 UNION
SELECT team FROM m_LJ_FINAL_2022 UNION
SELECT team FROM m_SP_FINAL_2022 UNION
SELECT team FROM m_HJ_FINAL_2022 UNION
SELECT team FROM m_DT_FINAL_2022 UNION
SELECT team FROM m_TJ_FINAL_2022 UNION
SELECT team FROM M_DEC_final_2015 UNION
SELECT team FROM M_DEC_final_2016 UNION
SELECT team FROM M_DEC_final_2017 UNION
SELECT team FROM M_DEC_final_2018 UNION
SELECT team FROM M_DEC_final_2019 UNION
SELECT team FROM M_DEC_final_2021 UNION
SELECT team FROM M_DEC_final_2022 UNION
SELECT team FROM W_100M_FINAL_2015 UNION
SELECT team FROM W_100M_FINAL_2016 UNION
SELECT team FROM W_100M_FINAL_2017 UNION
SELECT team FROM W_100M_FINAL_2018 UNION
SELECT team FROM W_100M_FINAL_2019 UNION
SELECT team FROM W_100M_FINAL_2021 UNION
SELECT team FROM W_100M_FINAL_2022 UNION
SELECT team FROM W_100M_SEMIS_2015 UNION
SELECT team FROM W_100M_SEMIS_2016 UNION
SELECT team FROM W_100M_SEMIS_2017 UNION
SELECT team FROM W_100M_SEMIS_2018 UNION
SELECT team FROM W_100M_SEMIS_2019 UNION
SELECT team FROM W_100M_SEMIS_2021 UNION
SELECT team FROM W_100M_SEMIS_2022 UNION
SELECT team FROM W_10K_FINAL_2015 UNION
SELECT team FROM W_10K_FINAL_2016 UNION
SELECT team FROM W_10K_FINAL_2017 UNION
SELECT team FROM W_10K_FINAL_2018 UNION
SELECT team FROM W_10K_FINAL_2019 UNION
SELECT team FROM W_10K_FINAL_2021 UNION
SELECT team FROM W_10K_FINAL_2022 UNION
SELECT team FROM W_100H_FINAL_2015 UNION
SELECT team FROM W_100H_FINAL_2016 UNION
SELECT team FROM W_100H_FINAL_2017 UNION
SELECT team FROM W_100H_FINAL_2018 UNION
SELECT team FROM W_100H_FINAL_2019 UNION
SELECT team FROM W_100H_FINAL_2021 UNION
SELECT team FROM W_100H_FINAL_2022 UNION
SELECT team FROM W_100H_SEMIS_2015 UNION
SELECT team FROM W_100H_SEMIS_2016 UNION
SELECT team FROM W_100H_SEMIS_2017 UNION
SELECT team FROM W_100H_SEMIS_2018 UNION
SELECT team FROM W_100H_SEMIS_2019 UNION
SELECT team FROM W_100H_SEMIS_2021 UNION
SELECT team FROM W_100H_SEMIS_2022 UNION
SELECT team FROM W_1500M_FINAL_2015 UNION
SELECT team FROM W_1500M_FINAL_2016 UNION
SELECT team FROM W_1500M_FINAL_2017 UNION
SELECT team FROM W_1500M_FINAL_2018 UNION
SELECT team FROM W_1500M_FINAL_2019 UNION
SELECT team FROM W_1500M_FINAL_2021 UNION
SELECT team FROM W_1500M_FINAL_2022 UNION
SELECT team FROM W_1500M_SEMIS_2015 UNION
SELECT team FROM W_1500M_SEMIS_2016 UNION
SELECT team FROM W_1500M_SEMIS_2017 UNION
SELECT team FROM W_1500M_SEMIS_2018 UNION
SELECT team FROM W_1500M_SEMIS_2019 UNION
SELECT team FROM W_1500M_SEMIS_2021 UNION
SELECT team FROM W_1500M_SEMIS_2022 UNION
SELECT team FROM W_200M_FINAL_2015 UNION
SELECT team FROM W_200M_FINAL_2016 UNION
SELECT team FROM W_200M_FINAL_2017 UNION
SELECT team FROM W_200M_FINAL_2018 UNION
SELECT team FROM W_200M_FINAL_2019 UNION
SELECT team FROM W_200M_FINAL_2021 UNION
SELECT team FROM W_200M_FINAL_2022 UNION
SELECT team FROM W_200M_SEMIS_2015 UNION
SELECT team FROM W_200M_SEMIS_2016 UNION
SELECT team FROM W_200M_SEMIS_2017 UNION
SELECT team FROM W_200M_SEMIS_2018 UNION
SELECT team FROM W_200M_SEMIS_2019 UNION
SELECT team FROM W_200M_SEMIS_2021 UNION
SELECT team FROM W_200M_SEMIS_2022 UNION
SELECT team FROM W_3000mSC_FINAL_2015 UNION
SELECT team FROM W_3000mSC_FINAL_2016 UNION
SELECT team FROM W_3000mSC_FINAL_2017 UNION
SELECT team FROM W_3000mSC_FINAL_2018 UNION
SELECT team FROM W_3000mSC_FINAL_2019 UNION
SELECT team FROM W_3000mSC_FINAL_2021 UNION
SELECT team FROM W_3000mSC_FINAL_2022 UNION
SELECT team FROM W_3000mSC_SEMIS_2015 UNION
SELECT team FROM W_3000mSC_SEMIS_2016 UNION
SELECT team FROM W_3000mSC_SEMIS_2017 UNION
SELECT team FROM W_3000mSC_SEMIS_2018 UNION
SELECT team FROM W_3000mSC_SEMIS_2019 UNION
SELECT team FROM W_3000mSC_SEMIS_2021 UNION
SELECT team FROM W_3000mSC_SEMIS_2022 UNION
SELECT team FROM W_400H_FINAL_2015 UNION
SELECT team FROM W_400H_FINAL_2016 UNION
SELECT team FROM W_400H_FINAL_2017 UNION
SELECT team FROM W_400H_FINAL_2018 UNION
SELECT team FROM W_400H_FINAL_2019 UNION
SELECT team FROM W_400H_FINAL_2021 UNION
SELECT team FROM W_400H_FINAL_2022 UNION
SELECT team FROM W_400H_SEMIS_2015 UNION
SELECT team FROM W_400H_SEMIS_2016 UNION
SELECT team FROM W_400H_SEMIS_2017 UNION
SELECT team FROM W_400H_SEMIS_2018 UNION
SELECT team FROM W_400H_SEMIS_2019 UNION
SELECT team FROM W_400H_SEMIS_2021 UNION
SELECT team FROM W_400H_SEMIS_2022 UNION
SELECT team FROM W_400M_FINAL_2015 UNION
SELECT team FROM W_400M_FINAL_2016 UNION
SELECT team FROM W_400M_FINAL_2017 UNION
SELECT team FROM W_400M_FINAL_2018 UNION
SELECT team FROM W_400M_FINAL_2019 UNION
SELECT team FROM W_400M_FINAL_2021 UNION
SELECT team FROM W_400M_FINAL_2022 UNION
SELECT team FROM W_400M_SEMIS_2015 UNION
SELECT team FROM W_400M_SEMIS_2016 UNION
SELECT team FROM W_400M_SEMIS_2017 UNION
SELECT team FROM W_400M_SEMIS_2018 UNION
SELECT team FROM W_400M_SEMIS_2019 UNION
SELECT team FROM W_400M_SEMIS_2021 UNION
SELECT team FROM W_400M_SEMIS_2022 UNION
SELECT team FROM W_4x1_FINAL_2015 UNION
SELECT team FROM W_4x1_FINAL_2016 UNION
SELECT team FROM W_4x1_FINAL_2017 UNION
SELECT team FROM W_4x1_FINAL_2018 UNION
SELECT team FROM W_4x1_FINAL_2019 UNION
SELECT team FROM W_4x1_FINAL_2021 UNION
SELECT team FROM W_4x1_FINAL_2022 UNION
SELECT team FROM W_4x1_SEMIS_2015 UNION
SELECT team FROM W_4x1_SEMIS_2016 UNION
SELECT team FROM W_4x1_SEMIS_2017 UNION
SELECT team FROM W_4x1_SEMIS_2018 UNION
SELECT team FROM W_4x1_SEMIS_2019 UNION
SELECT team FROM W_4x1_SEMIS_2021 UNION
SELECT team FROM W_4x1_SEMIS_2022 UNION
SELECT team FROM W_4x4_FINAL_2015 UNION
SELECT team FROM W_4x4_FINAL_2016 UNION
SELECT team FROM W_4x4_FINAL_2017 UNION
SELECT team FROM W_4x4_FINAL_2018 UNION
SELECT team FROM W_4x4_FINAL_2019 UNION
SELECT team FROM W_4x4_FINAL_2021 UNION
SELECT team FROM W_4x4_FINAL_2022 UNION
SELECT team FROM W_4x4_SEMIS_2015 UNION
SELECT team FROM W_4x4_SEMIS_2016 UNION
SELECT team FROM W_4x4_SEMIS_2017 UNION
SELECT team FROM W_4x4_SEMIS_2018 UNION
SELECT team FROM W_4x4_SEMIS_2019 UNION
SELECT team FROM W_4x4_SEMIS_2021 UNION
SELECT team FROM W_4x4_SEMIS_2022 UNION
SELECT team FROM W_5K_FINAL_2015 UNION
SELECT team FROM W_5K_FINAL_2016 UNION
SELECT team FROM W_5K_FINAL_2017 UNION
SELECT team FROM W_5K_FINAL_2018 UNION
SELECT team FROM W_5K_FINAL_2019 UNION
SELECT team FROM W_5K_FINAL_2021 UNION
SELECT team FROM W_5K_FINAL_2022 UNION
SELECT team FROM W_800M_FINAL_2015 UNION
SELECT team FROM W_800M_FINAL_2016 UNION
SELECT team FROM W_800M_FINAL_2017 UNION
SELECT team FROM W_800M_FINAL_2018 UNION
SELECT team FROM W_800M_FINAL_2019 UNION
SELECT team FROM W_800M_FINAL_2021 UNION
SELECT team FROM W_800M_FINAL_2022 UNION
SELECT team FROM W_800M_SEMIS_2015 UNION
SELECT team FROM W_800M_SEMIS_2016 UNION
SELECT team FROM W_800M_SEMIS_2017 UNION
SELECT team FROM W_800M_SEMIS_2018 UNION
SELECT team FROM W_800M_SEMIS_2019 UNION
SELECT team FROM W_800M_SEMIS_2021 UNION
SELECT team FROM W_800M_SEMIS_2022 UNION
SELECT team FROM W_HT_FINAL_2015 UNION
SELECT team FROM W_PV_FINAL_2015 UNION
SELECT team FROM W_JT_FINAL_2015 UNION
SELECT team FROM W_LJ_FINAL_2015 UNION
SELECT team FROM W_SP_FINAL_2015 UNION
SELECT team FROM W_HJ_FINAL_2015 UNION
SELECT team FROM W_DT_FINAL_2015 UNION
SELECT team FROM W_TJ_FINAL_2015 UNION
SELECT team FROM W_HT_FINAL_2016 UNION
SELECT team FROM W_PV_FINAL_2016 UNION
SELECT team FROM W_JT_FINAL_2016 UNION
SELECT team FROM W_LJ_FINAL_2016 UNION
SELECT team FROM W_SP_FINAL_2016 UNION
SELECT team FROM W_HJ_FINAL_2016 UNION
SELECT team FROM W_DT_FINAL_2016 UNION
SELECT team FROM W_TJ_FINAL_2016 UNION
SELECT team FROM W_HT_FINAL_2017 UNION
SELECT team FROM W_PV_FINAL_2017 UNION
SELECT team FROM W_JT_FINAL_2017 UNION
SELECT team FROM W_LJ_FINAL_2017 UNION
SELECT team FROM W_SP_FINAL_2017 UNION
SELECT team FROM W_HJ_FINAL_2017 UNION
SELECT team FROM W_DT_FINAL_2017 UNION
SELECT team FROM W_TJ_FINAL_2017 UNION
SELECT team FROM W_HT_FINAL_2018 UNION
SELECT team FROM W_PV_FINAL_2018 UNION
SELECT team FROM W_JT_FINAL_2018 UNION
SELECT team FROM W_LJ_FINAL_2018 UNION
SELECT team FROM W_SP_FINAL_2018 UNION
SELECT team FROM W_HJ_FINAL_2018 UNION
SELECT team FROM W_DT_FINAL_2018 UNION
SELECT team FROM W_TJ_FINAL_2018 UNION
SELECT team FROM W_HT_FINAL_2019 UNION
SELECT team FROM W_PV_FINAL_2019 UNION
SELECT team FROM W_JT_FINAL_2019 UNION
SELECT team FROM W_LJ_FINAL_2019 UNION
SELECT team FROM W_SP_FINAL_2019 UNION
SELECT team FROM W_HJ_FINAL_2019 UNION
SELECT team FROM W_DT_FINAL_2019 UNION
SELECT team FROM W_HT_FINAL_2021 UNION
SELECT team FROM W_PV_FINAL_2021 UNION
SELECT team FROM W_JT_FINAL_2021 UNION
SELECT team FROM W_LJ_FINAL_2021 UNION
SELECT team FROM W_SP_FINAL_2021 UNION
SELECT team FROM W_HJ_FINAL_2021 UNION
SELECT team FROM W_DT_FINAL_2021 UNION
SELECT team FROM W_TJ_FINAL_2021 UNION
SELECT team FROM W_HT_FINAL_2022 UNION
SELECT team FROM W_PV_FINAL_2022 UNION
SELECT team FROM W_JT_FINAL_2022 UNION
SELECT team FROM W_LJ_FINAL_2022 UNION
SELECT team FROM W_SP_FINAL_2022 UNION
SELECT team FROM W_HJ_FINAL_2022 UNION
SELECT team FROM W_DT_FINAL_2022 UNION
SELECT team FROM W_TJ_FINAL_2022 UNION
SELECT team FROM W_HEPT_final_2015 UNION
SELECT team FROM W_HEPT_final_2016 UNION
SELECT team FROM W_HEPT_final_2017 UNION
SELECT team FROM W_HEPT_final_2018 UNION
SELECT team FROM W_HEPT_final_2019 UNION
SELECT team FROM W_HEPT_final_2021 UNION
SELECT team FROM W_HEPT_final_2022;



/* Championship by Year Views */
	CREATE VIEW M_NCAA_2022_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2022 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2022 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2022 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2022 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2022 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2022 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2022 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2022;

CREATE VIEW M_NCAA_2021_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2021 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2021 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2021 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2021 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2021 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2021 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2021 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2021;

CREATE VIEW M_NCAA_2019_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2019 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2019 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2019 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2019 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2019 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2019 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2019 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2019;

CREATE VIEW M_NCAA_2018_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2018 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2018 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2018 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2018 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2018 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2018 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2018 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2018;

CREATE VIEW M_NCAA_2017_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2017 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2017 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2017 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2017 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2017 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2017 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2017 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2017;

CREATE VIEW M_NCAA_2016_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2016 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2016 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2016 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2016 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2016 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2016 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2016 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2016;

 CREATE VIEW M_NCAA_2015_Champs_VW as
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as Reaction_Time,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_LJ_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HJ_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_SP_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,plACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_DT_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_JT_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_PV_final_2015 UNION ALL
	SELECT EVENT,SEASON,Null as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,null as Wind,Score FROM M_HT_final_2015 union ALL
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,Mark as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,Flight_pl as Section_pl,Wind,Score FROM M_TJ_final_2015 union all
	SELECT Event,Season,NUll as Round,PLACE,Name,Year,Team,null as MARK,null as TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,null as Section_pl,null as Wind,Score FROM M_DEC_final_2015 union all
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND, SCORE FROM M_100m_final_2015 UNION ALL	
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_100m_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_200m_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_200m_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400m_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE  FROM M_400m_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_800m_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_800m_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_1500m_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_1500m_final_2015 UNION ALL 
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_3000mSC_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_3000mSC_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,WIND,NULL AS SCORE FROM M_110H_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,WIND,SCORE FROM M_110H_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_400H_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_400H_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_5K_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,YEAR,TEAM,Time as MARK,TIME_DETAIL,null as REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_10K_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x1_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x1_final_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,QUALIFIER,heat_pl as Section_pl,NULL AS WIND,NULL AS SCORE FROM M_4x4_semis_2015 UNION ALL
	SELECT EVENT,SEASON,ROUND,PLACE,NAME,null as YEAR,TEAM,Time as MARK,TIME_DETAIL,REACTION_TIME,NULL AS QUALIFIER,NULL AS Section_pl,NULL AS WIND,SCORE FROM M_4x4_final_2015;
