/* EVENT VIEWS */
CREATE VIEW VW_W_100 as
select * from (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100m_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND,  SCORE FROM W_100m_final_2023
    ) as M100
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;


CREATE VIEW VW_W_200 as
select * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_200m_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_200m_final_2023
    ) as M200
ORDER BY CASE
        WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
        ELSE 999999
        END,
        time;



CREATE VIEW VW_W_400 as
select * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400m_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400m_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400m_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400M_FINAL_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400M_SEMIS_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400M_FINAL_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400M_SEMIS_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400M_FINAL_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400M_SEMIS_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400m_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400m_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400m_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400m_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400m_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400m_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE  FROM W_400m_final_2023
    ) as M400
ORDER BY CASE
        WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
        ELSE 999999
        END,
        time;

CREATE VIEW VW_W_800 as
    select * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_800m_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_800m_final_2023
    ) as M800
ORDER BY CASE
        WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
        ELSE 999999
        END,
        time;

CREATE VIEW VW_W_1500 as
   select * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_1500m_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_1500m_final_2023
    ) as M1500
ORDER BY CASE
        WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
        ELSE 999999
        END,
        time;

CREATE VIEW VW_W_3000mSC as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_3000mSC_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_3000mSC_final_2023
    ) as M300mSC
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_100H as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, WIND, NULL AS SCORE FROM W_100H_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, WIND, SCORE FROM W_100H_final_2023
    ) as M100H
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_400H as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_SEMIS_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_400H_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_400H_final_2023
    ) as M400H
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_5K as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_5K_final_2023
    ) as M5K
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_10K as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, TIME, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_10K_final_2023
    ) as M10K
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_4x1 as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x1_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x1_final_2023
    ) as M4X1
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_4x4 as
    SELECT * FROM (
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2015 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2016 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2017 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2018 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2019 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2021 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2022 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, QUALIFIER, heat_pl, NULL AS WIND, NULL AS SCORE FROM W_4x4_semis_2023 UNION ALL
    SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, TIME, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS heat_pl, NULL AS WIND, SCORE FROM W_4x4_final_2023
    ) as M4X4
ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

CREATE VIEW VW_W_TJ_final as (
   select * from (
        select * FROM W_TJ_final_2015 union all
        select * FROM W_TJ_final_2016 union all
        select * FROM W_TJ_final_2017 union all
        select * FROM W_TJ_final_2018 union all
        select * FROM W_TJ_final_2019 union all
        select * FROM W_TJ_final_2021 union all
        select * FROM W_TJ_final_2022 union all
        select * FROM W_TJ_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_HJ_final as (
    select * from  (
        select * FROM W_HJ_final_2015 union all
        select * FROM W_HJ_final_2016 union all
        select * FROM W_HJ_final_2017 union all
        select * FROM W_HJ_final_2018 union all
        select * FROM W_HJ_final_2019 union all
        select * FROM W_HJ_final_2021 union all
        select * FROM W_HJ_final_2022 union all
        select * FROM W_HJ_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_LJ_final as (
    select * from (
        select * FROM W_LJ_final_2015 union all
        select * FROM W_LJ_final_2016 union all
        select * FROM W_LJ_final_2017 union all
        select * FROM W_LJ_final_2018 union all
        select * FROM W_LJ_final_2019 union all
        select * FROM W_LJ_final_2021 union all
        select * FROM W_LJ_final_2022 union all
        select * FROM W_LJ_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
  );

CREATE VIEW VW_W_SP_final as (
    select * from (
        select * FROM W_SP_final_2015 union all
        select * FROM W_SP_final_2016 union all
        select * FROM W_SP_final_2017 union all
        select * FROM W_SP_final_2018 union all
        select * FROM W_SP_final_2019 union all
        select * FROM W_SP_final_2021 union all
        select * FROM W_SP_final_2022 union ALL
        select * FROM W_SP_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_DT_final as (
    select * from (
        select * FROM W_DT_final_2015 union all
        select * FROM W_DT_final_2016 union all
        select * FROM W_DT_final_2017 union all
        select * FROM W_DT_final_2018 union all
        select * FROM W_DT_final_2019 union all
        select * FROM W_DT_final_2021 union all
        select * FROM W_DT_final_2022 union all
        select * FROM W_DT_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_HT_final as (
    select * from (    
        select * FROM W_HT_final_2015 union all
        select * FROM W_HT_final_2016 union all
        select * FROM W_HT_final_2017 union all
        select * FROM W_HT_final_2018 union all
        select * FROM W_HT_final_2019 union all
        select * FROM W_HT_final_2021 union all
        select * FROM W_HT_final_2022 union all
        select * FROM W_HT_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_PV_final as (
    select * from (
        select * FROM W_PV_final_2015 union all
        select * FROM W_PV_final_2016 union all
        select * FROM W_PV_final_2017 union all
        select * FROM W_PV_final_2018 union all
        select * FROM W_PV_final_2019 union all
        select * FROM W_PV_final_2021 union all
        select * FROM W_PV_final_2022 union ALL
        select * FROM W_PV_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
);

CREATE VIEW VW_W_JT_final as (
    select * from (
    select * FROM W_JT_final_2015 union all
    select * FROM W_JT_final_2016 union all
    select * FROM W_JT_final_2017 union all
    select * FROM W_JT_final_2018 union all
    select * FROM W_JT_final_2019 union all
    select * FROM W_JT_final_2021 union all
    select * FROM W_JT_final_2022 union all
    select * FROM W_JT_final_2023
) mark
ORDER BY 
  CASE 
    WHEN mark ~ '^[0-9\.]+$' THEN CAST(mark AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  mark desc
  );

CREATE VIEW VW_W_HEPT_final as (
    select * from (
    select * FROM W_HEPT_final_2015 union all
    select * FROM W_HEPT_final_2016 union all
    select * FROM W_HEPT_final_2017 union all
    select * FROM W_HEPT_final_2018 union all
    select * FROM W_HEPT_final_2019 union all
    select * FROM W_HEPT_final_2021 union all
    select * FROM W_HEPT_final_2022 union all
    select * FROM W_HEPT_final_2023
) HEPT
ORDER BY 
  CASE 
    WHEN points ~ '^[0-9\.]+$' THEN CAST(points AS FLOAT) 
    ELSE NULL 
  END DESC NULLS LAST, 
  points desc
  );
  

/* ORDERED ADDTIONAL VIEWS */
/* Fastest time by year */
select * from (
	SELECT *, MIN(place) OVER(PARTITION BY TEAM) AS LOWEST_place
	FROM VW_W_4x4
	) as best_finish
where lowest_place = place
and upper(round) = 'FINAL';

/*Fastest time ran by each Team */
select * from (
	SELECT *, MIN(TIME) OVER(PARTITION BY TEAM) AS LOWEST_TIME
	FROM VW_W_4x4
	) as TEAM_FASTEST
where lowest_time = time;

/*Fastest time ran at all NCAA's */
select * from (
	SELECT *, row_number() OVER(PARTITION BY TEAM) AS rnum
	FROM VW_W_4x4
	) as TEAM_FASTEST
where rnum = 1
	ORDER BY CASE
         WHEN time ~ '^[0-9\.]+$' THEN CAST(time AS FLOAT)
         ELSE 999999
         END,
         time;

