CREATE TABLE W_HT_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2015 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2016 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2017 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2018 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2019 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2022 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HT_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_PV_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_JT_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_LJ_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_SP_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_HJ_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_DT_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	--,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);

CREATE TABLE W_TJ_FINAL_2021 (
	EVENT VARCHAR(10)
	,season INT
	,ROUND VARCHAR(10)
	,PLACE VARCHAR(10)
	,Name VARCHAR(50)
	,Team VARCHAR(50)
	,Year VARCHAR(10)
	,Mark VARCHAR(50)
	,Wind VARCHAR(50)
	,"Flight(pl)" VARCHAR(50)
	,Score INT
	);
