
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,1,'Denzel COMENENTIA','JR','Georgia','76.41','2 (1)','10');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,2,'Anders ERIKSSON','JR','Florida','73.76','2 (4)','8');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,3,'Jake NORRIS','FR','LSU','73.24','1 (1)','6');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,4,'Rudy WINKLER','SR','Rutgers','72.74','2 (2)','5');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,5,'Daniel HAUGH','JR','Alabama','72.72','2 (5)','4');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,6,'Morgan SHIGO','JR','Penn State','72.47','1 (2)','3');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,7,'Thomas MARDAL','FR','Florida','72.20','2 (3)','2');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,8,'AJ MCFARLAND','JR','Florida','71.29','1 (3)','1');
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,9,'Adam KELLY','JR','Princeton','70.27','1 (4)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,10,'Kevin ARREAGA','FR','Miami','70.07','1 (5)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,11,'Hilmar ORN JONSSON','JR','Virginia','69.94','2 (6)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,12,'Gleb DUDAREV','SO','Kansas','69.18','2 (7)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,13,'Michael SHANAHAN','SR','New Hampshire','69.16','1 (6)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,14,'Brock EAGER','JR','Washington St.','67.97','2 (8)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,15,'Cristian RAVAR LADISLAU','SR','Arkansas State','67.75','2 (9)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,16,'Silviu BOCANCEA','JR','California','65.54','2 (10)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,17,'Justin STAFFORD','JR','UCLA','64.25','2 (11)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,18,'Mitch DIXON','SR','Kansas State','64.17','1 (7)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,19,'Joshua HERNANDEZ','SO','Sam Houston St.','63.46','1 (8)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,20,'Ricky HURLEY','SO','Southern Illinois','63.07','1 (9)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,21,'Kieran MCKEAG','FR','Minnesota','62.45','1 (10)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,22,'Avery CARTER','JR','Missouri','62.21','1 (11)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,23,'Nicholas PERCY','SR','Nebraska','61.70','2 (12)',null);
insert into m_HT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HT',2018,24,'Jacob MCBRIDE','SR','North Dakota State','60.75','1 (12)',null);

insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,1,'Chris NILSEN','SO','South Dakota','5.83','1 (1)','10');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,2,'Matthew LUDWIG','JR','Akron','5.55','1 (2)','8');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,3,'Torben LAIDIG','SR','Virginia Tech','5.55','1 (3)','6');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,4,'Jacob WOOTEN','JR','Texas A&M','5.55','1 (4)','5');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,5,'Tray OATES','SR','Samford','5.45','1 (5)','4');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,5,'Hussain AL HIZAM','JR','Kansas','5.45','1 (5)','3');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,7,'Deakin VOLZ','JR','Virginia Tech','5.45','1 (7)','2');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,8,'Joel BENITEZ','FR','Virginia Tech','5.45','1 (8)','1');
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,9,'Adam COULON','SO','Indiana','5.45','1 (9)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,10,'Marc TONEY','SR','UC Davis','5.45','1 (10)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,11,'Nate RICHARTZ','SR','Notre Dame','5.30','1 (11)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,11,'Sean COLLINS','JR','South Alabama','5.30','1 (11)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,13,'Drew MCMICHAEL','JR','Texas Tech','5.30','1 (13)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,14,'Audie WYATT','SR','Texas A&M','5.30','1 (14)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,15,'Blake SCOTT','JR','Oklahoma State','5.30','1 (15)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,16,'Craig HUNTER','SR','Connecticut','5.30','1 (16)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,17,'Sander MOLDAU','FR','Washington St.','5.15','1 (17)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,17,'Elijah COLE','SO','Charlotte','5.15','1 (17)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,19,'Clayton FRITSCH','FR','Sam Houston St.','5.15','1 (19)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,20,'Scott MARSHALL','SR','Grand Canyon','5.15','1 (20)',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,null,'Nick MEYER','SR','Kansas','NH','1',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,null,'Cole GORSKI','SR','Ohio State','NH','1',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,null,'Jake DAVID','JR','South Dakota','NH','1',null);
insert into m_PV_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('PV',2018,null,'Devin KING','SR','SE Louisiana',null,'1',null);

insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,1,'Anderson PETERS','FR','Miss State','82.82','2 (1)','10');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,2,'Nicolas QUIJERA','SR','Miss State','80.21','2 (2)','8');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,3,'Sindri GUDMUNDSSON','SO','Utah State','76.37','2 (3)','6');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,4,'Trevor DANIELSON','JR','Stanford','71.80','1 (1)','5');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,5,'Michael CRITICOS','SR','Memphis','71.25','2 (6)','4');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,6,'Elijah MARTA','SR','Kentucky','70.81','1 (2)','3');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,7,'Fabian DOHMANN','SR','Texas','70.58','2 (4)','2');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,8,'Aaron TRUE','JR','Wichita State','70.26','2 (5)','1');
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,9,'Jesse NEWMAN','SO','Grand Canyon','69.81','1 (3)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,10,'Jonno ENGELKING','SO','SE Missouri','68.07','2 (7)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,11,'Marian SPANNOWSKY','SO','UCLA','68.05','1 (4)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,12,'Adrian WILLIAMS','JR','SE Louisiana','68.01','1 (5)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,13,'William PETERSSON','SO','Texas A&M','67.33','1 (6)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,14,'Simon LITZELL','SO','UCLA','66.72','2 (8)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,15,'Michael BIDDLE','SO','Penn State','66.52','1 (7)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,16,'Tony WHITE','SR','UMBC','65.71','2 (9)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,17,'Denzel PRATT','JR','Liberty','65.19','2 (10)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,18,'John NIZICH','JR','Oregon','64.30','2 (11)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,19,'Richard VINSON','SR','SE Missouri','63.58','1 (8)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,20,'Damien ODLE','SR','Wichita State','63.47','1 (9)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,21,'Rodrigo IGLESIAS','JR','Akron','63.23','1 (10)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,22,'Sean RICHARDS','SR','Navy','61.35','1 (11)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,23,'August COOK','FR','Army West Point','61.10','2 (12)',null);
insert into m_JT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('JT',2018,24,'Cade ANTONUCCI','FR','Auburn','59.30','1 (12)',null);

insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,1,'Zack BAZILE','SR','Ohio State','8.37','1.9','1 (1)','10');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,2,'Jordan LATIMER','JR','Akron','8.02','1.8','2 (1)','8');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,3,'Odaine LEWIS','JR','Texas Tech','7.99','3.7','1 (2)','6');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,4,'Rayvon GREY','SO','LSU','7.96','3.1','1 (3)','5');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,5,'Charles BROWN','JR','Texas Tech','7.90','2.4','1 (5)','4');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,6,'Kyle DARROW','SR','Northeastern','7.88','1.8','1 (4)','3');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,7,'KeAndre BATES','SR','Florida','7.86','0.5','2 (3)','2');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,8,'Tahar TRIKI','SO','Texas A&M','7.86','0.4','2 (2)','1');
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,9,'Grant HOLLOWAY','SO','Florida','7.83','0.1','2 (4)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,10,'Damarcus SIMPSON','SR','Oregon','7.81','1.2','1 (6)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,11,'Terrell MCCLAIN','SR','Akron','7.77','2.8','1 (7)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,12,'Julian HARVEY','SR','SIU Edwardsville','7.76','1.8','1 (8)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,13,'Yann RANDRIANASOLO','JR','South Carolina','7.73','1.4','1 (9)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,14,'Harrison SCHRAGE','SO','Arkansas','7.70','2.0','2 (5)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,15,'Jonathan WELLS','JR','Illinois','7.65','0.7','2 (6)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,16,'Kenneth FISHER','SR','Florida State','7.65','1.9','2 (7)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,17,'Jacob FINCHAM-DUKES','JR','Oklahoma State','7.60','0.4','1 (10)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,18,'Saladin NASSER','SR','Long Beach St.','7.48','2.4','2 (8)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,19,'JuVaughn BLAKE','FR','LSU','7.48','0.9','1 (11)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,20,'Jason SMITH','SO','Long Beach St.','7.42','0.4','1 (12)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,21,'Marcus FLANNIGAN','SR','Grand Canyon','7.38','1.4','2 (9)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,22,'Fred DORSEY','SR','Kentucky','7.35','-0.4','2 (10)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,23,'Carter SHELL','FR','Arkansas State','7.30','0.3','2 (11)',null);
insert into m_LJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,Wind,"Flight(pl)",Score) values ('LJ',2018,null,'Tyler JONES','FR','Kennesaw State','FOUL',null,'2',null);


insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,1,'Denzel COMENENTIA','JR','Georgia','20.61','1 (3)','10');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,2,'Josh AWOTUNDE','SR','South Carolina','20.57','1 (6)','8');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,3,'Mostafa HASSAN','SR','Colorado St.','20.44','1 (1)','6');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,4,'Adrian PIPERI','FR','Texas','20.41','1 (4)','5');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,5,'Jordan GEIST','FR','Arizona','20.32','1 (2)','4');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,6,'Oghenakpobo EFEKORO','JR','Virginia','20.28','1 (5)','3');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,7,'Austin DROOGSMA','SR','Florida State','20.23','2 (1)','2');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,8,'Nicholas DEMALINE','SR','Ohio State','20.18','2 (2)','1');
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,9,'Jared KERN','SR','Southern Illinois','19.95','2 (3)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,10,'Payton OTTERDAHL','JR','North Dakota State','19.62','1 (7)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,11,'Grant CARTWRIGHT','SR','Michigan','19.61','2 (4)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,12,'Jordan WEST','FR','Tennessee','19.43','2 (5)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,13,'Kord FERGUSON','JR','Alabama','19.39','1 (8)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,14,'Andrew LISKOWITZ','SO','Michigan','19.19','1 (9)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,15,'Nicholas PONZIO','SR','USC','19.01','2 (6)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,16,'Peter SIMON','SR','California','18.95','1 (10)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,17,'McKay JOHNSON','SO','California','18.92','1 (11)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,18,'T''Mond JOHNSON','JR','Texas State','18.91','2 (7)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,19,'Noah CASTLE','JR','Kentucky','18.91','1 (12)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,20,'Nikolas HUFFMAN','SR','Kentucky','18.54','2 (8)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,21,'Brett NEELLY','JR','Kansas State','18.04','2 (9)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,22,'Itamar LEVI','SR','Arkansas State','17.92','2 (10)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,23,'Reno TUUFULI','JR','Iowa','17.89','2 (11)',null);
insert into m_SP_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('SP',2018,null,'Cedric PAUL','SR','Northwestern St.','FOUL','2',null);

insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,1,'Tejaswin SHANKAR','FR','Kansas State','2.24','1 (1)','10');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,2,'Shelby MCEWEN','SO','Alabama','2.21','1 (2)','8');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,3,'Keenon LAINE','JR','Georgia','2.21','1 (3)','6');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,4,'Trey CULVER','SR','Texas Tech','2.21','1 (4)','5');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,5,'Antonios MERLOS','FR','Georgia','2.18','1 (5)','4');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,6,'Vernon TURNER','FR','Oklahoma','2.18','1 (6)','3');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,7,'Earnie SEARS','FR','USC','2.18','1 (7)','2');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,8,'Jhonny VICTOR','JR','Florida','2.18','1 (8)','1');
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,9,'Landon BARTEL','SR','Nebraska','2.18','1 (9)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,10,'Clayton BROWN','SO','Florida','2.13','1 (10)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,10,'Damar ROBINSON','SR','Louisville','2.13','1 (10)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,12,'Samuel SHOULTZ','JR','Maryland','2.13','1 (12)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,13,'JuVaughn BLAKE','FR','LSU','2.08','1 (13)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,13,'Ty ANDERSON','SR','UTSA','2.08','1 (13)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,13,'Jonathan WELLS','JR','Illinois','2.08','1 (13)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,13,'Zack ANDERSON','SO','South Dakota','2.08','1 (13)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,13,'Matthew BIRZER','JR','Notre Dame','2.08','1 (13)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,18,'Ryan LOCKARD','SR','Minnesota','2.08','1 (18)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,18,'Ben MILLIGAN','JR','Oregon','2.08','1 (18)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,18,'Brandon PIWINSKI','FR','Michigan','2.08','1 (18)',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,null,'Safir SCOTT','FR','Connecticut','NH','1',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,null,'Julian HARVEY','SR','SIU Edwardsville','NH','1',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,null,'Bryant O''GEORGIA','JR','Arizona','NH','1',null);
insert into m_HJ_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('HJ',2018,null,'Jerin ALLEN','SR','Louisville','NH','1',null);

insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,1,'Luke VAUGHN','SR','Memphis','60.41','2 (1)','10');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,2,'Greg THOMPSON','JR','Maryland','58.96','2 (2)','8');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,3,'Brian WILLIAMS','SR','Ole Miss','58.62','2 (3)','6');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,4,'Kord FERGUSON','JR','Alabama','58.42','1 (1)','5');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,5,'Reno TUUFULI','JR','Iowa','57.61','2 (7)','4');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,6,'Ashmon LUCAS','SO','Purdue','56.88','2 (4)','3');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,7,'David LUCAS','JR','Penn State','56.87','2 (5)','2');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,8,'Nicholas PERCY','SR','Nebraska','56.72','2 (8)','1');
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,9,'Eric KICINSKI','JR','Texas Tech','56.55','2 (6)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,10,'Payton OTTERDAHL','JR','North Dakota State','55.48','1 (2)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,11,'Daniel HAUGH','JR','Alabama','55.27','2 (9)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,12,'Jordan GEIST','FR','Arizona','54.95','1 (3)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,13,'George EVANS','FR','Kansas','54.41','2 (10)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,14,'Nicolai CEBAN','SR','Kansas','54.26','1 (4)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,15,'Rafael VALLERY','SR','Memphis','53.98','1 (5)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,16,'Noah CASTLE','JR','Kentucky','53.95','1 (6)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,17,'Kyle DOUGLASS','SR','Montana State','53.91','1 (7)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,18,'McKay JOHNSON','SO','California','53.43','2 (11)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,19,'Turner WASHINGTON','FR','Arizona','53.36','1 (8)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,20,'Gian RAGONESI','SR','Miami','52.77','1 (9)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,21,'Cullen PRENA','SR','Ole Miss','51.47','1 (10)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,22,'Irenej BOZOVICAR','SR','Manhattan','51.46','1 (11)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,23,'Carlos DAVIS','JR','Nebraska','49.10','2 (12)',null);
insert into m_DT_final_2018 (Event,Season,Place,Name,Year,Team,Mark,"Flight(pl)",Score) values ('DT',2018,null,'Ben HAMMER','JR','South Dakota','FOUL','1',null);

insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,1,'Tahar TRIKI','SO','Texas A&M','16.79','-0.7','1 (1)','10');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,2,'Odaine LEWIS','JR','Texas Tech','16.73','0.6','1 (4)','8');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,3,'KeAndre BATES','SR','Florida','16.63','0.0','1 (2)','6');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,4,'Scotty NEWTON','SR','TCU','16.47','-0.7','1 (3)','5');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,5,'Chengetayi MAPAYA','FR','TCU','16.42','0.5','2 (1)','4');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,6,'Christian EDWARDS','FR','Alabama','16.37','0.2','2 (3)','3');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,7,'Darius ARMSTEAD','SR','Sacramento St.','16.17','-0.1','1 (5)','2');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,8,'Clayton BROWN','SO','Florida','16.10','-0.5','1 (6)','1');
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,9,'Kaiwan CULMER','SR','Nebraska','16.09','0.0','2 (2)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,10,'Jordan SCOTT','SO','Virginia','15.96','-0.2','1 (7)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,11,'Barden ADAMS','SR','Kansas','15.90','-0.6','1 (8)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,12,'Brian MADA','JR','DePaul','15.89','-0.2','2 (4)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,13,'David OLUWADARA','SR','Boston U.','15.86','0.1','2 (5)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,14,'Papay GLAYWULU','FR','Oklahoma','15.86','0.3','1 (9)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,15,'John WARREN','JR','Southern Miss.','15.86','-0.9','1 (10)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,16,'DaJuan SEWARD','JR','Ohio State','15.75','-0.4','1 (11)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,17,'Jeremiah GREEN','SR','Clemson','15.71','0.5','2 (6)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,18,'Tuomas KAUKOLAHTI','JR','California','15.53','-0.9','2 (7)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,19,'Craig STEVENS JR','JR','Kent State','15.36','-0.5','2 (8)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,20,'Markel DALTON','JR','Charlotte','15.14','-0.1','2 (9)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,21,'Darrel JONES','SR','Liberty','15.00','-0.2','2 (10)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,22,'Zachary JOHNSON','FR','Sam Houston St.','13.32','-0.8','2 (11)',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,null,'OnullBrien WASOME','SO','Texas','DNS',null,'2',null);
insert into m_TJ_final_2018 (Event,Season,Place,Name,YEAR,TEAM,Mark,Wind,"Flight(pl)",Score) values ('TJ',2018,null,'Armani WALLACE','JR','Florida State','FOUL',null,'1',null);
