insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,1,'Rudy WINKLER','SR','Cornell',74.12,'2 (1)',10);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,2,'Alexander YOUNG','SR','SE Louisiana',73.66,'2 (7)',8);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,3,'Gleb DUDAREV','FR','Kansas',73.44,'2 (6)',6);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,4,'Hilmar ORN JONSSON','SO','Virginia',72.38,'2 (2)',5);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,5,'Denzel COMENENTIA','SO','Georgia',71.75,'2 (3)',4);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,6,'Johnnie JACKSON','SR','LSU',71.72,'2 (4)',3);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,7,'Alex POURSANIDIS','SR','Georgia',71.44,'2 (5)',2);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,8,'Joseph ELLIS','SO','Michigan',70.33,'1 (1)',1);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,9,'Jordan YOUNG','SR','Virginia',69.71,'1 (2)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,10,'Dempsey MCGUIGAN','SR','Ole Miss',69.14,'1 (3)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,11,'Adam KEENAN','SR','Northern Arizona',68.98,'2 (8)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,12,'Cameron BROWN','SR','Tennessee',68.55,'1 (4)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,13,'Joshua HERNANDEZ','FR','Sam Houston St.',66.95,'2 (9)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,14,'Brock EAGER','SO','Washington St.',66.16,'2 (10)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,15,'Seth WHITENER','SO','Tennessee',66.14,'1 (5)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,16,'Cristian RAVAR LADISLAU','JR','Arkansas State',65.33,'2 (11)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,17,'Trevor TROUTMAN','SR','Louisville',65.09,'1 (6)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,18,'Austin RIDDLE','JR','Rice',64.94,'2 (12)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,19,'Riley BUDDE','JR','Wisconsin',63.15,'1 (7)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,20,'Mitch DIXON','JR','Kansas State',62.91,'1 (8)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,21,'Brady GRUNDER','SR','Kansas State',62.71,'1 (9)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,22,'Kyle SMITH','SR','Kansas State',61.54,'1 (10)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,23,'Austin COOK','JR','Texas A&M',60.00,'1 (11)',null);
insert into m_HT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"FLIGHT(PL)",SCORE) values ('HT',2017,24,'Cullen PRENA','JR','Oregon',59.75,'1 (12)',null);

insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,1,'Matthew LUDWIG','SO','Akron','5.60','1 (1)','10');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,2,'Adrian VALLES','JR','Cincinnati','5.55','1 (2)','8');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,3,'Hussain ALHIZAM','SO','Kansas','5.45','1 (3)','5.5');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,3,'Chris NILSEN','FR','South Dakota','5.45','1 (3)','5.5');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,5,'Cole WALSH','JR','Oregon','5.45','1 (5)','3.5');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,5,'Jacob WOOTEN','SO','Texas A&M','5.45','1 (5)','3.5');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,7,'Audie WYATT','JR','Texas A&M','5.45','1 (7)','2');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,8,'Sean COLLINS','SO','South Alabama','5.45','1 (8)','1');
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,9,'Nate RICHARTZ','JR','Notre Dame','5.45','1 (9)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,10,'Devin KING','JR','SE Louisiana','5.30','1 (10)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,11,'Barrett POTH','JR','Texas','5.30','1 (11)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,12,'Will HERRSCHER','SO','Alabama','5.30','1 (12)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,12,'Jake ALBRIGHT','SR','Kansas','5.30','1 (12)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,14,'Noah GARY','JR','Michigan State','5.30','1 (14)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,15,'Sean CLARKE','FR','Penn','5.30','1 (15)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,16,'Garrett STARKEY','SR','Arizona State','5.15','1 (16)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,16,'Brad JOHNSON','SR','Virginia Tech','5.15','1 (16)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,18,'Everette FAVOR','SR','Oklahoma','5.15','1 (18)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,18,'Carl JOHANSSON','JR','Texas A&M','5.15','1 (18)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,20,'Connor HALL','SR','Duke','5.15','1 (20)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,20,'Rashid COULIBALY','FR','Wisconsin','5.15','1 (20)',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,null,'Armand WOODLEY','SO','South Carolina','NH','1',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,null,'August KILES','JR','Princeton','NH','1',null);
insert into m_PV_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('PV',2017,null,'Antonio RUIZ','SO','Stephen F. Austin','NH','NH',null);

insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,1,'Ioannis KYRIAZIS','JR','Texas A&M',82.58,'2 (1)','10');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,2,'Nicolas QUIJERA','JR','Miss State',76.77,'2 (2)','8');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,3,'Michael SHUEY','SR','Penn State',76.42,'2 (6)','6');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,4,'Alex PASCAL','JR','Missouri',75.38,'2 (3)','5');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,5,'Matti MORTIMORE','JR','N. Dakota St.',74.33,'2 (4)','4');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,6,'Sindri GUDMUNDSSON','FR','Utah State',73.28,'2 (5)','3');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,7,'Curtis THOMPSON','JR','Miss State',72.47,'2 (7)','2');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,8,'Chris MIRABELLI','JR','Rutgers',71.68,'2 (8)','1');
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,9,'Ryan KERR','SR','Penn State',70.71,'1 (1)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,10,'McLean LIPSCHUTZ','SR','Alabama',69.41,'1 (2)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,11,'Sam HARDIN','JR','Texas A&M',69.34,'2 (9)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,12,'Cody DANIELSON','SR','Oregon',69.31,'1 (3)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,13,'Michael CRITICOS','JR','Memphis',69.18,'2 (10)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,14,'Adrian MITCHELL','FR','Albany',68.54,'1 (4)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,15,'Matthew KUSKEY','SR','UC Santa Barbara',68.25,'1 (5)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,16,'Simon LITZELL','FR','UCLA',67.62,'1 (6)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,17,'Werner BOUWER','FR','Texas Tech',67.60,'1 (7)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,18,'Michael BIDDLE','FR','Penn State',66.95,'2 (11)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,19,'Reinhard VAN ZYL','SR','Missouri',66.86,'2 (12)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,20,'Emron GIBBS','SR','Southern Miss.',66.76,'1 (8)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,21,'Seth DERR','SR','Nebraska',66.05,'1 (9)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,22,'Ethan SHALAWAY','JR','Kentucky',65.02,'1 (10)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,23,'Marian SPANNOWSKY','FR','UCLA',64.90,'1 (11)',null);
insert into m_JT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,MARK,"Flight(pl)",SCORE) values ('JT',2017,24,'Tucker RIZZI','JR','William and Mary',60.91,'1 (12)',null);

insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,1,'KeAndre BATES','JR','Florida',8.05,'-1.1','2 (3)','10');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,2,'Grant HOLLOWAY','FR','Florida',8.00,'-0.5','2 (1)','8');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,3,'Will WILLIAMS','JR','Texas A&M',7.96,'0.3','2 (2)','6');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,4,'Terrell MCCLAIN','JR','Akron',7.80,'2.2','2 (7)','5');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,5,'Chris MCBRIDE','SO','Clemson',7.71,'0.2','2 (4)','4');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,6,'Eric SLOAN','JR','USC',7.65,'0.9','2 (5)','3');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,7,'Carlos BECKER','FR','Florida State',7.63,'0.7','1 (1)','2');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,8,'Andreas TRAJKOVSKI','SR','Arkansas',7.62,'0.4','2 (6)','1');
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,9,'Jacob FINCHAM-DUKES','SO','Oklahoma State',7.61,'0.1','2 (8)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,10,'OnullBrien WASOME','FR','Texas',7.58,'1.5','1 (2)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,11,'Scotty NEWTON','JR','TCU',7.51,'0.4','1 (3)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,12,'Justin HALL','FR','Texas Tech',7.48,'0.2','2 (9)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,13,'Isaiah GRIFFITH','FR','Nebraska',7.47,'1.1','1 (4)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,14,'Jamie BROWN','SO','Alabama State',7.46,'-0.5','1 (5)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,15,'Adrian RILEY','JR','UTSA',7.44,'0.8','2 (10)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,16,'Harrison SCHRAGE','FR','Arkansas',7.40,'1.0','1 (6)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,17,'Cory BARGER','JR','Sacramento St.',7.34,'0.3','1 (7)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,18,'Malik MOFFETT','JR','Penn State',7.32,'0.9','1 (8)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,19,'Willie REED','JR','Miss State',7.28,'1.2','2 (11)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,20,'Ventavius SEARS','SR','Western Kentucky',7.26,'1.1','1 (9)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,21,'OnullShea WILSON','JR','Iowa',7.20,'1.2','1 (10)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,22,'Zack BAZILE','JR','Ohio State',7.14,'1.0','2 (12)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,23,'Samory FRAGA','SO','Kent State',6.99,'0.1','1 (11)',null);
insert into m_LJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('LJ',2017,null,'Fred DORSEY','JR','Kentucky','FOUL',null,'1',null);

insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,1,'Filip MIHALJEVIC','SR','Virginia',21.30,'2 (1)','10');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,2,'Mostafa HASSAN','JR','Colorado St.',20.38,'2 (2)','8');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,3,'Nicholas DEMALINE','JR','Ohio State',20.08,'2 (3)','6');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,4,'Oghenakpobo EFEKORO','SO','Virginia',19.70,'1 (1)','5');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,5,'Denzel COMENENTIA','SO','Georgia',19.63,'2 (4)','4');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,6,'Nicholas PONZIO','JR','USC',19.53,'2 (5)','3');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,7,'Peter SIMON','JR','California',19.49,'2 (6)','2');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,8,'Alex RENNER','SR','N. Dakota St.',19.26,'2 (7)','1');
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,9,'Willie MORRISON','SO','Indiana',18.97,'2 (8)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,10,'Lucas WARNING','SR','Lehigh',18.94,'1 (2)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,11,'Jon YOHMAN','JR','Penn State',18.91,'2 (9)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,12,'Austin DROOGSMA','JR','Florida State',18.89,'2 (10)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,13,'Nikolas HUFFMAN','JR','Kentucky',18.81,'1 (3)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,14,'Riley BUDDE','JR','Wisconsin',18.73,'1 (4)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,15,'Aaron CASTLE','SR','Arizona',18.67,'1 (5)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,16,'Matthew KATNIK','SO','USC',18.63,'2 (11)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,17,'Nicolai CEBAN','JR','Kansas',18.60,'2 (12)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,18,'Brett NEELLY','SO','Kansas State',18.58,'1 (6)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,19,'Josh AWOTUNDE','JR','South Carolina',18.52,'1 (7)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,20,'Zachary STETLER','SR','BYU',18.49,'1 (8)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,21,'TnullMond JOHNSON','SO','Texas State',18.31,'1 (9)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,22,'Grant CARTWRIGHT','JR','Michigan',18.21,'1 (10)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,23,'Andrew LISKOWITZ','FR','Michigan',17.57,'1 (11)',null);
insert into m_SP_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('SP',2017,24,'Josh MCDONALD','JR','Wisconsin',17.09,'1 (12)',null);

insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,1,'Christoff BRYAN','JR','Kansas State','2.21','1 (1)','10');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,2,'Trey CULVER','JR','Texas Tech','2.21','1 (2)','8');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,3,'Justice SUMMERSET','FR','Arizona','2.18','1 (3)','6');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,4,'Tye WILLIAMS','JR','South Carolina','2.13','1 (4)','4.5');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,4,'Keenon LAINE','SO','Georgia','2.13','1 (4)','4.5');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,6,'Jalen FORD','JR','Iowa State','2.13','1 (6)','3');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,7,'Jerin ALLEN','JR','Louisville','2.13','1 (7)','1.5');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,7,'Jhonny VICTOR','SO','Florida','2.13','1 (7)','1.5');
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,9,'Clayton BROWN','FR','Florida','2.13','1 (9)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,9,'Jonathan WELLS','JR','Illinois','2.13','1 (9)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,9,'Eric BLACKMAN','JR','Purdue','2.13','1 (9)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,12,'Michael BURKE','SO','UCLA','2.13','1 (12)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,13,'Michael MCCANN','JR','Nebraska','2.08','1 (13)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,13,'Matthew BIRZER','SO','Notre Dame','2.08','1 (13)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,15,'Tiaan STEENKAMP','JR','Arkansas State','2.08','1 (15)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,15,'Landon BARTEL','JR','Nebraska','2.08','1 (15)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,15,'Garrett CRAGIN','JR','Texas A&M','2.08','1 (15)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,15,'Kyle LANDON','SR','Southern Illinois','2.08','1 (15)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,19,'Vincent CALHOUN','JR','Long Beach St.','2.08','1 (19)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,19,'Chris SULLIVAN','SR','FIU','2.08','1 (19)',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,null,'EdnullRicus WILLIAMS','SR','Florida State','NH','1',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,null,'Cody STINE','SO','Akron','NH','1',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,null,'Keyth FIGHTMASTER','SO','Samford','NH','1',null);
insert into m_HJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('HJ',2017,null,'Justin KRETCHMER','SR','Kentucky','NH','1',null);

insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,1,'Filip MIHALJEVIC','SR','Virginia',63.76,'1 (1)','10');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,2,'Reginald JAGERS','SR','Kent State',62.51,'2 (1)','8');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,3,'Jordan YOUNG','SR','Virginia',61.94,'2 (2)','6');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,4,'Brian WILLIAMS','JR','Ole Miss',59.95,'2 (5)','5');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,5,'Reno TUUFULI','SO','Iowa',59.81,'2 (3)','4');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,6,'Mitchell COOPER','SR','Kansas',59.12,'2 (4)','3');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,7,'Marek BARTA','JR','Virginia Tech',58.99,'2 (6)','2');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,8,'Kyle LONG','SR','Arizona State',58.09,'1 (2)','1');
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,9,'David LUCAS','SO','Penn State',58.00,'1 (3)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,10,'Macklin TUDOR','SR','Cincinnati',57.86,'2 (7)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,11,'Joe WILLIAMS','SR','Alabama',57.39,'1 (4)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,12,'Emmanuel ONYIA','SR','Florida State',56.79,'2 (8)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,13,'Nicolai CEBAN','JR','Kansas',56.66,'1 (5)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,14,'Nicholas PERCY','JR','Nebraska',56.15,'2 (9)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,15,'Greg THOMPSON','SO','Maryland',56.01,'1 (6)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,16,'Phillip JAGERS','SR','Akron',55.72,'2 (10)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,17,'Jayson KOVAR','SR','Southern Utah',54.91,'2 (11)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,18,'Matthew ZAJAC','JR','Tennessee',54.81,'1 (7)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,19,'Dotun OGUNDEJI','SO','UCLA',54.76,'1 (8)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,20,'Ryan HUNTER-SIMMS','SR','Oregon',53.07,'2 (12)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,21,'Ryan CAMP','FR','TCU',51.93,'1 (9)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,22,'Avery MEYERS','SR','Iowa',51.51,'1 (10)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,23,'Trevor KINTYHTT','SR','DePaul',51.07,'1 (11)',null);
insert into m_DT_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,"Flight(pl)",SCORE) values ('DT',2017,24,'Nicholas COGHILL','FR','Nebraska',47.87,'1 (12)',null);

insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,1,'KeAndre BATES','JR','Florida',16.76,'2.4','2 (1)','10');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,2,'Clive PULLEN','SR','Arkansas',16.60,'1.7','2 (2)','8');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,3,'Scott CARTER','SR','Wyoming',16.24,'1.4','1 (1)','6');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,4,'Hayden MCCLAIN','SR','Oklahoma',16.17,'1.8','2 (3)','5');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,5,'Barden ADAMS','JR','Kansas',16.08,'1.4','2 (4)','4');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,6,'Montel NEVERS','SO','Florida State',16.05,'2.7','1 (2)','3');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,7,'Craig STEVENS JR','SO','Kent State',16.00,'1.3','1 (3)','2');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,8,'Samuel TRIGG','SR','New Mexico',15.97,'2.2','2 (5)','1');
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,9,'Armani WALLACE','SO','Florida State',15.97,'2.3','1 (4)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,10,'Scotty NEWTON','JR','TCU',15.86,'2','1 (5)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,11,'Clayton BROWN','FR','Florida',15.82,'-1.2','2 (6)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,12,'Michael TILLER','SR','Bethune-Cookman',15.73,'2.5','2 (7)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,13,'Jeffrey PROTHRO','SR','Texas A&M',15.70,'1.5','2 (8)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,14,'Felix OBI','SR','Baylor',15.66,'2','1 (6)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,15,'Efe UWAIFO','SR','Harvard',15.65,'2.1','1 (7)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,16,'Eric SLOAN','JR','USC',15.62,'1.7','2 (9)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,17,'Bryce WILLIAMS','SO','Penn State',15.59,'0.7','2 (10)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,18,'Jordan SCOTT','FR','Virginia',15.50,'2.3','2 (11)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,19,'Jaden PURNELL','SO','Oral Roberts',15.50,'1.7','1 (8)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,20,'Antwon JAMES','SR','Iowa',15.38,'2.8','1 (9)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,21,'Isaiah GRIFFITH','FR','Nebraska',15.13,'1.8','1 (10)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,22,'Eric BETHEA','SO','Indiana',15.03,'3.1','1 (11)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,23,'Klyvens DELAUNAY','SR','Alabama',14.58,'1.1','1 (12)',null);
insert into m_TJ_final_2017 (Event,Season,Place,Name,YEAR,TEAM,Mark,WIND,"Flight(pl)",SCORE) values ('TJ',2017,null,'Lasheon STROZIER','SO','N. Carolina A&T','FOUL',null,'2',null);
