/* List of Teams */
CREATE VIEW TEAMS  as
SELECT team FROM  M_100M_FINAL_2015 UNION
SELECT team FROM  M_100M_FINAL_2016 UNION
SELECT team FROM  M_100M_FINAL_2017 UNION
SELECT team FROM  M_100M_FINAL_2018 UNION
SELECT team FROM  M_100M_FINAL_2019 UNION
SELECT team FROM  M_100M_FINAL_2021 UNION
SELECT team FROM  M_100M_FINAL_2022 UNION
SELECT team FROM  M_100M_SEMIS_2015 UNION
SELECT team FROM  M_100M_SEMIS_2016 UNION
SELECT team FROM  M_100M_SEMIS_2017 UNION
SELECT team FROM  M_100M_SEMIS_2018 UNION
SELECT team FROM  M_100M_SEMIS_2019 UNION
SELECT team FROM  M_100M_SEMIS_2021 UNION
SELECT team FROM  M_100M_SEMIS_2022 UNION
SELECT team FROM  M_10K_FINAL_2015 UNION
SELECT team FROM  M_10K_FINAL_2016 UNION
SELECT team FROM  M_10K_FINAL_2017 UNION
SELECT team FROM  M_10K_FINAL_2018 UNION
SELECT team FROM  M_10K_FINAL_2019 UNION
SELECT team FROM  M_10K_FINAL_2021 UNION
SELECT team FROM  M_10K_FINAL_2022 UNION
SELECT team FROM  M_110H_FINAL_2015 UNION
SELECT team FROM  M_110H_FINAL_2016 UNION
SELECT team FROM  M_110H_FINAL_2017 UNION
SELECT team FROM  M_110H_FINAL_2018 UNION
SELECT team FROM  M_110H_FINAL_2019 UNION
SELECT team FROM  M_110H_FINAL_2021 UNION
SELECT team FROM  M_110H_FINAL_2022 UNION
SELECT team FROM  M_110H_SEMIS_2015 UNION
SELECT team FROM  M_110H_SEMIS_2016 UNION
SELECT team FROM  M_110H_SEMIS_2017 UNION
SELECT team FROM  M_110H_SEMIS_2018 UNION
SELECT team FROM  M_110H_SEMIS_2019 UNION
SELECT team FROM  M_110H_SEMIS_2021 UNION
SELECT team FROM  M_110H_SEMIS_2022 UNION
SELECT team FROM  M_1500M_FINAL_2015 UNION
SELECT team FROM  M_1500M_FINAL_2016 UNION
SELECT team FROM  M_1500M_FINAL_2017 UNION
SELECT team FROM  M_1500M_FINAL_2018 UNION
SELECT team FROM  M_1500M_FINAL_2019 UNION
SELECT team FROM  M_1500M_FINAL_2021 UNION
SELECT team FROM  M_1500M_FINAL_2022 UNION
SELECT team FROM  M_1500M_SEMIS_2015 UNION
SELECT team FROM  M_1500M_SEMIS_2016 UNION
SELECT team FROM  M_1500M_SEMIS_2017 UNION
SELECT team FROM  M_1500M_SEMIS_2018 UNION
SELECT team FROM  M_1500M_SEMIS_2019 UNION
SELECT team FROM  M_1500M_SEMIS_2021 UNION
SELECT team FROM  M_1500M_SEMIS_2022 UNION
SELECT team FROM  M_200M_FINAL_2015 UNION
SELECT team FROM  M_200M_FINAL_2016 UNION
SELECT team FROM  M_200M_FINAL_2017 UNION
SELECT team FROM  M_200M_FINAL_2018 UNION
SELECT team FROM  M_200M_FINAL_2019 UNION
SELECT team FROM  M_200M_FINAL_2021 UNION
SELECT team FROM  M_200M_FINAL_2022 UNION
SELECT team FROM  M_200M_SEMIS_2015 UNION
SELECT team FROM  M_200M_SEMIS_2016 UNION
SELECT team FROM  M_200M_SEMIS_2017 UNION
SELECT team FROM  M_200M_SEMIS_2018 UNION
SELECT team FROM  M_200M_SEMIS_2019 UNION
SELECT team FROM  M_200M_SEMIS_2021 UNION
SELECT team FROM  M_200M_SEMIS_2022 UNION
SELECT team FROM  M_3000M_SC_FINAL_2015 UNION
SELECT team FROM  M_3000M_SC_FINAL_2016 UNION
SELECT team FROM  M_3000M_SC_FINAL_2017 UNION
SELECT team FROM  M_3000M_SC_FINAL_2018 UNION
SELECT team FROM  M_3000M_SC_FINAL_2019 UNION
SELECT team FROM  M_3000M_SC_FINAL_2021 UNION
SELECT team FROM  M_3000M_SC_FINAL_2022 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2015 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2016 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2017 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2018 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2019 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2021 UNION
SELECT team FROM  M_3000M_SC_SEMIS_2022 UNION
SELECT team FROM  M_400H_FINAL_2015 UNION
SELECT team FROM  M_400H_FINAL_2016 UNION
SELECT team FROM  M_400H_FINAL_2017 UNION
SELECT team FROM  M_400H_FINAL_2018 UNION
SELECT team FROM  M_400H_FINAL_2019 UNION
SELECT team FROM  M_400H_FINAL_2021 UNION
SELECT team FROM  M_400H_FINAL_2022 UNION
SELECT team FROM  M_400H_SEMIS_2015 UNION
SELECT team FROM  M_400H_SEMIS_2016 UNION
SELECT team FROM  M_400H_SEMIS_2017 UNION
SELECT team FROM  M_400H_SEMIS_2018 UNION
SELECT team FROM  M_400H_SEMIS_2019 UNION
SELECT team FROM  M_400H_SEMIS_2021 UNION
SELECT team FROM  M_400H_SEMIS_2022 UNION
SELECT team FROM  M_400M_FINAL_2015 UNION
SELECT team FROM  M_400M_FINAL_2016 UNION
SELECT team FROM  M_400M_FINAL_2017 UNION
SELECT team FROM  M_400M_FINAL_2018 UNION
SELECT team FROM  M_400M_FINAL_2019 UNION
SELECT team FROM  M_400M_FINAL_2021 UNION
SELECT team FROM  M_400M_FINAL_2022 UNION
SELECT team FROM  M_400M_SEMIS_2015 UNION
SELECT team FROM  M_400M_SEMIS_2016 UNION
SELECT team FROM  M_400M_SEMIS_2017 UNION
SELECT team FROM  M_400M_SEMIS_2018 UNION
SELECT team FROM  M_400M_SEMIS_2019 UNION
SELECT team FROM  M_400M_SEMIS_2021 UNION
SELECT team FROM  M_400M_SEMIS_2022 UNION
SELECT team FROM  M_4x1_FINAL_2015 UNION
SELECT team FROM  M_4x1_FINAL_2016 UNION
SELECT team FROM  M_4x1_FINAL_2017 UNION
SELECT team FROM  M_4x1_FINAL_2018 UNION
SELECT team FROM  M_4x1_FINAL_2019 UNION
SELECT team FROM  M_4x1_FINAL_2021 UNION
SELECT team FROM  M_4x1_FINAL_2022 UNION
SELECT team FROM  M_4x1_SEMIS_2015 UNION
SELECT team FROM  M_4x1_SEMIS_2016 UNION
SELECT team FROM  M_4x1_SEMIS_2017 UNION
SELECT team FROM  M_4x1_SEMIS_2018 UNION
SELECT team FROM  M_4x1_SEMIS_2019 UNION
SELECT team FROM  M_4x1_SEMIS_2021 UNION
SELECT team FROM  M_4x1_SEMIS_2022 UNION
SELECT team FROM  M_4x4_FINAL_2015 UNION
SELECT team FROM  M_4x4_FINAL_2016 UNION
SELECT team FROM  M_4x4_FINAL_2017 UNION
SELECT team FROM  M_4x4_FINAL_2018 UNION
SELECT team FROM  M_4x4_FINAL_2019 UNION
SELECT team FROM  M_4x4_FINAL_2021 UNION
SELECT team FROM  M_4x4_FINAL_2022 UNION
SELECT team FROM  M_4x4_SEMIS_2015 UNION
SELECT team FROM  M_4x4_SEMIS_2016 UNION
SELECT team FROM  M_4x4_SEMIS_2017 UNION
SELECT team FROM  M_4x4_SEMIS_2018 UNION
SELECT team FROM  M_4x4_SEMIS_2019 UNION
SELECT team FROM  M_4x4_SEMIS_2021 UNION
SELECT team FROM  M_4x4_SEMIS_2022 UNION
SELECT team FROM  M_5K_FINAL_2015 UNION
SELECT team FROM  M_5K_FINAL_2016 UNION
SELECT team FROM  M_5K_FINAL_2017 UNION
SELECT team FROM  M_5K_FINAL_2018 UNION
SELECT team FROM  M_5K_FINAL_2019 UNION
SELECT team FROM  M_5K_FINAL_2021 UNION
SELECT team FROM  M_5K_FINAL_2022 UNION
SELECT team FROM  M_800M_FINAL_2015 UNION
SELECT team FROM  M_800M_FINAL_2016 UNION
SELECT team FROM  M_800M_FINAL_2017 UNION
SELECT team FROM  M_800M_FINAL_2018 UNION
SELECT team FROM  M_800M_FINAL_2019 UNION
SELECT team FROM  M_800M_FINAL_2021 UNION
SELECT team FROM  M_800M_FINAL_2022 UNION
SELECT team FROM  M_800M_SEMIS_2015 UNION
SELECT team FROM  M_800M_SEMIS_2016 UNION
SELECT team FROM  M_800M_SEMIS_2017 UNION
SELECT team FROM  M_800M_SEMIS_2018 UNION
SELECT team FROM  M_800M_SEMIS_2019 UNION
SELECT team FROM  M_800M_SEMIS_2021 UNION
SELECT team FROM  M_800M_SEMIS_2022 UNION
SELECT team FROM m_HT_FINAL_2015 UNION
SELECT team FROM m_PV_FINAL_2015 UNION
SELECT team FROM m_JT_FINAL_2015 UNION
SELECT team FROM m_LJ_FINAL_2015 UNION
SELECT team FROM m_SP_FINAL_2015 UNION
SELECT team FROM m_HJ_FINAL_2015 UNION
SELECT team FROM m_DT_FINAL_2015 UNION
SELECT team FROM m_TJ_FINAL_2015 UNION
SELECT team FROM m_HT_FINAL_2016 UNION
SELECT team FROM m_PV_FINAL_2016 UNION
SELECT team FROM m_JT_FINAL_2016 UNION
SELECT team FROM m_LJ_FINAL_2016 UNION
SELECT team FROM m_SP_FINAL_2016 UNION
SELECT team FROM m_HJ_FINAL_2016 UNION
SELECT team FROM m_DT_FINAL_2016 UNION
SELECT team FROM m_TJ_FINAL_2016 UNION
SELECT team FROM m_HT_FINAL_2017 UNION
SELECT team FROM m_PV_FINAL_2017 UNION
SELECT team FROM m_JT_FINAL_2017 UNION
SELECT team FROM m_LJ_FINAL_2017 UNION
SELECT team FROM m_SP_FINAL_2017 UNION
SELECT team FROM m_HJ_FINAL_2017 UNION
SELECT team FROM m_DT_FINAL_2017 UNION
SELECT team FROM m_TJ_FINAL_2017 UNION
SELECT team FROM m_HT_FINAL_2018 UNION
SELECT team FROM m_PV_FINAL_2018 UNION
SELECT team FROM m_JT_FINAL_2018 UNION
SELECT team FROM m_LJ_FINAL_2018 UNION
SELECT team FROM m_SP_FINAL_2018 UNION
SELECT team FROM m_HJ_FINAL_2018 UNION
SELECT team FROM m_DT_FINAL_2018 UNION
SELECT team FROM m_TJ_FINAL_2018 UNION
SELECT team FROM m_HT_FINAL_2019 UNION
SELECT team FROM m_PV_FINAL_2019 UNION
SELECT team FROM m_JT_FINAL_2019 UNION
SELECT team FROM m_LJ_FINAL_2019 UNION
SELECT team FROM m_SP_FINAL_2019 UNION
SELECT team FROM m_HJ_FINAL_2019 UNION
SELECT team FROM m_DT_FINAL_2019 UNION
SELECT team FROM m_HT_FINAL_2021 UNION
SELECT team FROM m_PV_FINAL_2021 UNION
SELECT team FROM m_JT_FINAL_2021 UNION
SELECT team FROM m_LJ_FINAL_2021 UNION
SELECT team FROM m_SP_FINAL_2021 UNION
SELECT team FROM m_HJ_FINAL_2021 UNION
SELECT team FROM m_DT_FINAL_2021 UNION
SELECT team FROM m_TJ_FINAL_2021 UNION
SELECT team FROM m_HT_FINAL_2022 UNION
SELECT team FROM m_PV_FINAL_2022 UNION
SELECT team FROM m_JT_FINAL_2022 UNION
SELECT team FROM m_LJ_FINAL_2022 UNION
SELECT team FROM m_SP_FINAL_2022 UNION
SELECT team FROM m_HJ_FINAL_2022 UNION
SELECT team FROM m_DT_FINAL_2022 UNION
SELECT team FROM m_TJ_FINAL_2022;



/* Championship by Year Views */
	CREATE VIEW NCAA_2022_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2022 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2022 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2022 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2022 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2022 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2022;

    CREATE VIEW NCAA_2021_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2021 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2021 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2021 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2021 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2021 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2021;

    CREATE VIEW NCAA_2019_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2019 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2019 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2019 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2019 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2019 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2019;

    CREATE VIEW NCAA_2018_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2018 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2018 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2018 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2018 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2018 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2018;

    CREATE VIEW NCAA_2017_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2017 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2017 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2017 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2017 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2017 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2017;

    CREATE VIEW NCAA_2016_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2016 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2016 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2016 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2016 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2016 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2016;

    CREATE VIEW NCAA_2015_Champs_VW as
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_100m_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND,  SCORE FROM m_100m_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_200m_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_200m_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400m_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE  FROM m_400m_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_800m_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_800m_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_1500m_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_1500m_final_2015 UNION ALL 
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_3000mSC_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_3000mSC_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", WIND, NULL AS SCORE FROM m_110H_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", WIND, SCORE FROM m_110H_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_400H_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_400H_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_5K_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, YEAR, TEAM, Time as Mark, TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_10K_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x1_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x1_final_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, QUALIFIER, "HEAT(pl)" as "Section(pl)", NULL AS WIND, NULL AS SCORE FROM m_4x4_semis_2015 UNION ALL
	SELECT EVENT, SEASON, ROUND, PLACE, NAME, null as YEAR, TEAM, Time as Mark, TIME_DETAIL, REACTION_TIME, NULL AS QUALIFIER, NULL AS "Section(pl)", NULL AS WIND, SCORE FROM m_4x4_final_2015 UNION all
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as Reaction_Time, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_LJ_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HJ_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_SP_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, plACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_DT_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_JT_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_PV_final_2015 UNION ALL
	SELECT EVENT, SEASON, Null as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", null as Wind, Score from m_HT_final_2015 union ALL
	SELECT Event, Season, NUll as Round, PLACE, Name, Year, Team, Mark as Mark, null as TIME_DETAIL, null as REACTION_TIME, NULL AS QUALIFIER, "Flight(pl)" as "Section(pl)", Wind, Score from m_TJ_final_2015;